=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Holiday" xmlns:tns="http://www.example.org/Holiday" elementFormDefault="qualified">





    <simpleType name="Weekday">
    	<restriction base="string">
    		<enumeration value="MONDAY"></enumeration>
    		<enumeration value="TUESDAY"></enumeration>
    		<enumeration value="WEDNESDAY"></enumeration>
    		<enumeration value="THURSDAY"></enumeration>
    		<enumeration value="FRIDAY"></enumeration>
    		<enumeration value="SATURDAY"></enumeration>
    		<enumeration value="SUNDAY"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="Month">
    	<restriction base="string">
    		<enumeration value="JANUARY"></enumeration>
    		<enumeration value="FEBRUARY"></enumeration>
    		<enumeration value="MARCH"></enumeration>
    		<enumeration value="MAY"></enumeration>
    		<enumeration value="JUNE"></enumeration>
    		<enumeration value="JULY"></enumeration>
    		<enumeration value="AUGUST"></enumeration>
    		<enumeration value="SEPTEMBER"></enumeration>
    		<enumeration value="OCTOBER"></enumeration>
    		<enumeration value="NOVEMBER"></enumeration>
    		<enumeration value="DECEMBER"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="RelativeToEastern">
    	<attribute name="days" type="int"></attribute>
    </complexType>
    
    <complexType name="RelativeToFixed">
    	<sequence>
    		<choice maxOccurs="1" minOccurs="1">
    			<element name="Days" type="int"></element>
    			<element name="Weekday" type="tns:Weekday"></element>
    		</choice>
    		<element name="When" maxOccurs="1" minOccurs="1" type="tns:When">
    		</element>
    		<element name="Date" type="tns:Fixed" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    

    

    <complexType name="Holidays">
        <sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="Fixed" type="tns:Fixed"></element>
        	</sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="RelativeToEastern" type="tns:RelativeToEastern">
        		</element>
        	</sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="RelativeToFixed" type="tns:RelativeToFixed">
        		</element>
        	</sequence>
        </sequence>




    </complexType>

    
    <element name="Configuration" type="tns:Configuration"></element>
    
    <complexType name="Configuration">
    	<sequence>
    		<element name="Holidays" type="tns:Holidays"></element>
    		<element name="SubConfigurations" type="tns:Configuration" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="hierarchy" type="string"></attribute>
    </complexType>

    <complexType name="Fixed">
    	<attribute name="month" type="tns:Month"></attribute>
    	<attribute name="day">
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="1"></minInclusive>
    				<maxInclusive value="31"></maxInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>


    <simpleType name="When">
    	<restriction base="string">
    		<enumeration value="BEFORE"></enumeration>
    		<enumeration value="AFTER"></enumeration>
    	</restriction>
    </simpleType>
</schema>

=== svendiedrichsen/jollyday/tags/v_0_3_1/jollyday/src/main/resources/Holidays_at.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="at" description="Austria"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="JANUARY" day="6" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="AUGUST" day="15" />
		<tns:Fixed month="OCTOBER" day="26" />
		<tns:Fixed month="NOVEMBER" day="1" />
		<tns:Fixed month="DECEMBER" day="8" />
		<tns:Fixed month="DECEMBER" day="24" />
		<tns:Fixed month="DECEMBER" day="25" />
		<tns:Fixed month="DECEMBER" day="26" />
		<tns:Fixed month="DECEMBER" day="31" />
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
		<tns:ChristianHoliday type="ASCENSION_DAY" />
		<tns:ChristianHoliday type="WHIT_MONDAY" />
		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="b" description="Burgenland">
		<tns:Holidays>
			<tns:Fixed month="NOVEMBER" day="11"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="k" description="Kärnten">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19"/>
			<tns:Fixed month="OCTOBER" day="10"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="nö" description="Niederösterreich">
		<tns:Holidays>
			<tns:Fixed month="NOVEMBER" day="15"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="oö" description="Oberösterreich">
		<tns:Holidays>
			<tns:Fixed month="MAY" day="4"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="s" description="Salzburg">
		<tns:Holidays>
			<tns:Fixed month="SEPTEMBER" day="24"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="st" description="Steiermark">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="t" description="Tirol">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="va" description="Vorarlberg">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="w" description="Wien">
		<tns:Holidays>
			<tns:Fixed month="NOVEMBER" day="15"/>
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_be.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="be" description="Belgium" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="JULY" day="21"/>
	  <tns:Fixed month="AUGUST" day="15"/>
	  <tns:Fixed month="NOVEMBER" day="1"/>
	  <tns:Fixed month="NOVEMBER" day="11"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:RelativeToEastern days="1"/>
	  <tns:RelativeToEastern days="39"/>
	  <tns:RelativeToEastern days="50"/>
  </tns:Holidays>
  <tns:SubConfigurations hierarchy="fl" description="Flemish community">
  	<tns:Holidays>
  		<tns:Fixed month="JULY" day="11"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="fr" description="French community">
  	<tns:Holidays>
  		<tns:Fixed month="SEPTEMBER" day="27"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="ge" description="German community">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="15"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_lv.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="lv" description="Latvia" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="MAY" day="4"/>
	  <tns:Fixed month="JUNE" day="23"/>
	  <tns:Fixed month="JUNE" day="24"/>
	  <tns:Fixed month="AUGUST" day="5"/>
	  <tns:Fixed month="AUGUST" day="15"/>
	  <tns:Fixed month="OCTOBER" day="8"/>
	  <tns:Fixed month="NOVEMBER" day="18"/>
	  <tns:Fixed month="DECEMBER" day="24"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:Fixed month="DECEMBER" day="26"/>
	  <tns:Fixed month="DECEMBER" day="31"/>
	  <tns:ChristianHoliday type="EASTER" />
	  <tns:ChristianHoliday type="EASTER_MONDAY"/>
	  <tns:ChristianHoliday type="GOOD_FRIDAY"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_pe.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="pe" description="Peru"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="JUNE" day="29"/>
	  <tns:Fixed month="JULY" day="28"/>
	  <tns:Fixed month="JULY" day="29"/>
	  <tns:Fixed month="AUGUST" day="30"/>
	  <tns:Fixed month="OCTOBER" day="8"/>
	  <tns:Fixed month="NOVEMBER" day="1"/>
	  <tns:Fixed month="DECEMBER" day="8"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
	  <tns:ChristianHoliday type="GOOD_FRIDAY"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/test/resources/holidays/Holidays_test_de_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="de" description="Germany" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
	  <tns:Fixed month="OCTOBER" day="3" />
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:Fixed month="DECEMBER" day="26"/>
	  <tns:Fixed month="APRIL" day="2"/>
	  <tns:Fixed month="APRIL" day="5"/>
	  <tns:Fixed month="MAY" day="13"/>
	  <tns:Fixed month="MAY" day="24"/>
  </tns:Holidays>
  <tns:SubConfigurations hierarchy="bb" description="Brandenburg">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="bw" description="Baden-Württenberg">
  	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="6"/>
  		<tns:Fixed month="NOVEMBER" day="1"/>
  		<tns:Fixed month="JUNE" day="3"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="by" description="Bayern">
  	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="6"/>
  		<tns:Fixed month="NOVEMBER" day="1"/>
  		<tns:Fixed month="JUNE" day="3"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="he" description="Hessen">
  	<tns:Holidays>
  		<tns:Fixed month="JUNE" day="3"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="mv" description="Mecklenburg-Vorpommern">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="nw" description="Nordrhein-Westfalen">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="1"/>
  		<tns:Fixed month="JUNE" day="3"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="rp" description="Rheinland-Pfalz">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="1"/>
  		<tns:Fixed month="JUNE" day="3"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sl" description="Saarland">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="1"/>
  		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:Fixed month="JUNE" day="3"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sn" description="Sachsen">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31"/>
  		<tns:Fixed month="NOVEMBER" day="17"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="st" description="Sachsen-Anhalt">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31"/>
  		<tns:Fixed month="JANUARY" day="6"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="th" description="Thüringen">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_ee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ee" description="Estonia" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
	  <tns:Fixed month="FEBRUARY" day="24" descriptionPropertiesKey="INDEPENDENCE"/>
	  <tns:Fixed month="JUNE" day="23" descriptionPropertiesKey="VICTORY"/>
	  <tns:Fixed month="JUNE" day="24" descriptionPropertiesKey="MIDSUMMER"/>
	  <tns:Fixed month="AUGUST" day="20" validFrom="1991" descriptionPropertiesKey="REST_INDEP" />
	  <tns:Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
	  <tns:ChristianHoliday type="EASTER" />
	  <tns:ChristianHoliday type="GOOD_FRIDAY"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_nl.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="nl" description="Netherlands" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="APRIL" day="30"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:Fixed month="DECEMBER" day="26"/>
	  <tns:RelativeToEastern days="-2"/>
	  <tns:RelativeToEastern days="1"/>
 	  <tns:RelativeToEastern days="39"/>
 	  <tns:RelativeToEastern days="50"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday-test/src/test/resources/holidays/Holidays_test_fr_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="fr" description="France"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="MAY" day="8" descriptionPropertiesKey="VICTORY_DAY"/>
		<tns:Fixed month="JULY" day="14" descriptionPropertiesKey="NATIONAL_DAY"/>
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_MARY"/>
		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
		<tns:Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="REMEMBRANCE"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="APRIL" day="5" descriptionPropertiesKey="EASTER_MONDAY"/>
		<tns:Fixed month="MAY" day="13" descriptionPropertiesKey="ASCENSION_DAY"/>
		<tns:Fixed month="MAY" day="24" descriptionPropertiesKey="WHIT_MONDAY"/>
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="ma"
		description="Martinique">
		<tns:Holidays>
			<tns:Fixed month="MAY" day="22" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="gu"
		description="Guadeloupe">
		<tns:Holidays>
			<tns:Fixed month="MAY" day="27" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="gy" description="Guyane">
		<tns:Holidays>
			<tns:Fixed month="JUNE" day="10" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="lr"
		description="La Reunion">
		<tns:Holidays>
			<tns:Fixed month="DECEMBER" day="20" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="br" description="Bas-Rhin">
		<tns:Holidays>
			<tns:Fixed month="DECEMBER" day="26" />
			<tns:ChristianHoliday type="GOOD_FRIDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="hr"
		description="Haut-Rhin">
		<tns:Holidays>
			<tns:Fixed month="DECEMBER" day="26" />
			<tns:ChristianHoliday type="GOOD_FRIDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="mo" description="Moselle">
		<tns:Holidays>
			<tns:Fixed month="DECEMBER" day="26" />
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>
