=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Holiday" xmlns:tns="http://www.example.org/Holiday" elementFormDefault="qualified">





    <simpleType name="Weekday">
    	<restriction base="string">
    		<enumeration value="MONDAY"></enumeration>
    		<enumeration value="TUESDAY"></enumeration>
    		<enumeration value="WEDNESDAY"></enumeration>
    		<enumeration value="THURSDAY"></enumeration>
    		<enumeration value="FRIDAY"></enumeration>
    		<enumeration value="SATURDAY"></enumeration>
    		<enumeration value="SUNDAY"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="Month">
    	<restriction base="string">
    		<enumeration value="JANUARY"></enumeration>
    		<enumeration value="FEBRUARY"></enumeration>
    		<enumeration value="MARCH"></enumeration>
    		<enumeration value="MAY"></enumeration>
    		<enumeration value="JUNE"></enumeration>
    		<enumeration value="JULY"></enumeration>
    		<enumeration value="AUGUST"></enumeration>
    		<enumeration value="SEPTEMBER"></enumeration>
    		<enumeration value="OCTOBER"></enumeration>
    		<enumeration value="NOVEMBER"></enumeration>
    		<enumeration value="DECEMBER"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="RelativeToEastern">
    	<attribute name="days" type="int"></attribute>
    </complexType>
    
    <complexType name="RelativeToFixed">
    	<sequence>
    		<choice maxOccurs="1" minOccurs="1">
    			<element name="Days" type="int"></element>
    			<element name="Weekday" type="tns:Weekday"></element>
    		</choice>
    		<element name="When" maxOccurs="1" minOccurs="1" type="tns:When">
    		</element>
    		<element name="Date" type="tns:Fixed" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    

    

    <complexType name="Holidays">
        <sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="Fixed" type="tns:Fixed"></element>
        	</sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="RelativeToEastern" type="tns:RelativeToEastern">
        		</element>
        	</sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="RelativeToFixed" type="tns:RelativeToFixed">
        		</element>
        	</sequence>
        </sequence>




    </complexType>

    
    <element name="Configuration" type="tns:Configuration"></element>
    
    <complexType name="Configuration">
    	<sequence>
    		<element name="Holidays" type="tns:Holidays"></element>
    		<element name="SubConfigurations" type="tns:Configuration" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="hierarchy" type="string"></attribute>
    </complexType>

    <complexType name="Fixed">
    	<attribute name="month" type="tns:Month"></attribute>
    	<attribute name="day">
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="1"></minInclusive>
    				<maxInclusive value="31"></maxInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>


    <simpleType name="When">
    	<restriction base="string">
    		<enumeration value="BEFORE"></enumeration>
    		<enumeration value="AFTER"></enumeration>
    	</restriction>
    </simpleType>
</schema>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_md.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="md" description="Moldova"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="JANUARY" day="7" />
		<tns:Fixed month="JANUARY" day="8" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="MAY" day="9" />
		<tns:Fixed month="AUGUST" day="27" />
		<tns:Fixed month="AUGUST" day="31" />
		<tns:Fixed month="OCTOBER" day="11" />
		<tns:Fixed month="OCTOBER" day="23" />
		<tns:Fixed month="DECEMBER" day="8" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="EASTER_MONDAY" chronology="JULIAN" />
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="ch" description="Chisinau">
		<tns:Holidays>
			<tns:Fixed month="MAY" day="22"/>
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_lt.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="lt" description="Lithuania"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="FEBRUARY" day="16" />
		<tns:Fixed month="MARCH" day="11" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="JUNE" day="24" />
		<tns:Fixed month="JULY" day="6" />
		<tns:Fixed month="AUGUST" day="15" />
		<tns:Fixed month="NOVEMBER" day="1" />
		<tns:Fixed month="DECEMBER" day="25" />
		<tns:Fixed month="DECEMBER" day="26" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_al.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="al" description="Albania" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="NOVEMBER" day="28"/>
	  <tns:Fixed month="NOVEMBER" day="29"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:RelativeToEastern days="-2"/>
	  <tns:RelativeToEastern days="1"/>
	  <tns:RelativeToEastern days="39"/>
	  <tns:RelativeToEastern days="50"/>
	  <tns:IslamicHoliday name="ID_UL_ADHA"/>
	  <tns:IslamicHoliday name="ID_AL_FITR"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_si.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="si" description="Slovenia"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="2" />
		<tns:Fixed month="FEBRUARY" day="8" />
		<tns:Fixed month="APRIL" day="23" />
		<tns:Fixed month="APRIL" day="27" />
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="MAY" day="2" />
		<tns:Fixed month="JUNE" day="25" />
		<tns:Fixed month="AUGUST" day="15" />
		<tns:Fixed month="OCTOBER" day="31" />
		<tns:Fixed month="NOVEMBER" day="1" />
		<tns:Fixed month="NOVEMBER" day="11" />
		<tns:Fixed month="OCTOBER" day="31" />
		<tns:Fixed month="DECEMBER" day="6" />
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="DECEMBER" day="26" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
		<tns:ChristianHoliday type="MARDI_GRAS"/>
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_hu.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="hu" description="Hungary"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="MARCH" day="15" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="AUGUST" day="20" />
		<tns:Fixed month="OCTOBER" day="23" />
		<tns:Fixed month="NOVEMBER" day="1" />
		<tns:Fixed month="DECEMBER" day="24" />
		<tns:Fixed month="DECEMBER" day="25" />
		<tns:Fixed month="DECEMBER" day="26" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
		<tns:ChristianHoliday type="WHIT_MONDAY" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_ec.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ec" description="Ecuador"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="MAY" day="24" descriptionPropertiesKey="PICHINCHA"/>
		<tns:Fixed month="JULY" day="24" descriptionPropertiesKey="BOLIVAR"/>
		<tns:Fixed month="AUGUST" day="10" descriptionPropertiesKey="INDEP_QUITO"/>
		<tns:Fixed month="OCTOBER" day="9" descriptionPropertiesKey="INDEP_GUYAQUIL"/>
		<tns:Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS"/>
		<tns:Fixed month="NOVEMBER" day="3" descriptionPropertiesKey="INDEP_CUENCA"/>
		<tns:Fixed month="DECEMBER" day="6" descriptionPropertiesKey="FOUND_QUITO"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE"/>
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="MAUNDY_THURSDAY" />
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/tags/v_0_4_5/tags/v_0_3_0/jollyday/src/main/resources/Holidays_br.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="br" description="Brazil"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="APRIL" day="21" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="SEPTEMBER" day="7" />
		<tns:Fixed month="OCTOBER" day="12" />
		<tns:Fixed month="NOVEMBER" day="2" />
		<tns:Fixed month="NOVEMBER" day="15" />
		<tns:Fixed month="DECEMBER" day="25"/>
		<tns:ChristianHoliday type="CARNIVAL"/>
		<tns:ChristianHoliday type="ASH_WEDNESDAY"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY"/>
		<tns:ChristianHoliday type="CORPUS_CHRISTI"/>
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="rj" description="Rio de Janeiro">
		<tns:Holidays>
			<tns:Fixed month="APRIL" day="23" validFrom="2007"/>
			<tns:Fixed month="NOVEMBER" day="20"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="crj" description="City of Rio de Janeiro">
			<tns:Holidays>
				<tns:Fixed month="JANUARY" day="20"/>
				<tns:Fixed month="APRIL" day="23" validTo="2006"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="s" description="Sao Paulo">
		<tns:Holidays>
			<tns:Fixed month="JULY" day="9"/>
			<tns:Fixed month="NOVEMBER" day="20"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="cs" description="City of Sao Paulo">
			<tns:Holidays>
				<tns:Fixed month="JANUARY" day="25"/>
				<tns:Fixed month="NOVEMBER" day="4"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="mg" description="Minas Gerais">
		<tns:Holidays></tns:Holidays>
		<tns:SubConfigurations hierarchy="bh" description="Belo Horizonte">
			<tns:Holidays>
				<tns:Fixed month="AUGUST" day="15"/>
				<tns:Fixed month="DECEMBER" day="8"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="ms" description="Mato Grosso do Sul">
		<tns:Holidays>
			<tns:Fixed month="OCTOBER" day="11"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="cg" description="Campo Grande">
			<tns:Holidays>
				<tns:Fixed month="AUGUST" day="26"/>
			</tns:Holidays>
		</tns:SubConfigurations>
		<tns:SubConfigurations hierarchy="do" description="Dourados">
			<tns:Holidays>
				<tns:Fixed month="DECEMBER" day="8"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="pr" description="Parana">
		<tns:Holidays></tns:Holidays>
		<tns:SubConfigurations hierarchy="cu" description="Curitiba">
			<tns:Holidays>
				<tns:Fixed month="SEPTEMBER" day="8"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="rs" description="Rio Grande do Sul">
		<tns:Holidays>
			<tns:Fixed month="SEPTEMBER" day="20"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="sm" description="Santa Maria">
			<tns:Holidays>
				<tns:Fixed month="DECEMBER" day="8"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="rn" description="Rio Grande do Norte">
		<tns:Holidays>
			<tns:Fixed month="OCTOBER" day="3"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="na" description="Natal">
			<tns:Holidays>
				<tns:Fixed month="NOVEMBER" day="21"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="go" description="GoiÃ¡s">
		<tns:Holidays>
			<tns:Fixed month="OCTOBER" day="24"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="pe" description="Pernambuco">
		<tns:Holidays>
			<tns:Fixed month="DECEMBER" day="8"/>
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_by.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="by" description="Belarus"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="MARCH" day="8" descriptionPropertiesKey="INTERNATIONAL_WOMAN"/>
		<tns:Fixed month="MARCH" day="15" descriptionPropertiesKey="CONSTITUTION_DAY"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="VICTORY"/>
		<tns:Fixed month="JULY" day="3" descriptionPropertiesKey="INDEPENDENCE"/>
		<tns:Fixed month="NOVEMBER" day="7" descriptionPropertiesKey="OCT_REVOLUTION"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	</tns:Holidays>
</tns:Configuration>
