=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Holiday" xmlns:tns="http://www.example.org/Holiday" elementFormDefault="qualified">





    <simpleType name="Weekday">
    	<restriction base="string">
    		<enumeration value="MONDAY"></enumeration>
    		<enumeration value="TUESDAY"></enumeration>
    		<enumeration value="WEDNESDAY"></enumeration>
    		<enumeration value="THURSDAY"></enumeration>
    		<enumeration value="FRIDAY"></enumeration>
    		<enumeration value="SATURDAY"></enumeration>
    		<enumeration value="SUNDAY"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="Month">
    	<restriction base="string">
    		<enumeration value="JANUARY"></enumeration>
    		<enumeration value="FEBRUARY"></enumeration>
    		<enumeration value="MARCH"></enumeration>
    		<enumeration value="MAY"></enumeration>
    		<enumeration value="JUNE"></enumeration>
    		<enumeration value="JULY"></enumeration>
    		<enumeration value="AUGUST"></enumeration>
    		<enumeration value="SEPTEMBER"></enumeration>
    		<enumeration value="OCTOBER"></enumeration>
    		<enumeration value="NOVEMBER"></enumeration>
    		<enumeration value="DECEMBER"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="RelativeToEastern">
    	<attribute name="days" type="int"></attribute>
    </complexType>
    
    <complexType name="RelativeToFixed">
    	<sequence>
    		<choice maxOccurs="1" minOccurs="1">
    			<element name="Days" type="int"></element>
    			<element name="Weekday" type="tns:Weekday"></element>
    		</choice>
    		<element name="When" maxOccurs="1" minOccurs="1" type="tns:When">
    		</element>
    		<element name="Date" type="tns:Fixed" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    

    

    <complexType name="Holidays">
        <sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="Fixed" type="tns:Fixed"></element>
        	</sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="RelativeToEastern" type="tns:RelativeToEastern">
        		</element>
        	</sequence>
        	<sequence maxOccurs="unbounded" minOccurs="0">
        		<element name="RelativeToFixed" type="tns:RelativeToFixed">
        		</element>
        	</sequence>
        </sequence>




    </complexType>

    
    <element name="Configuration" type="tns:Configuration"></element>
    
    <complexType name="Configuration">
    	<sequence>
    		<element name="Holidays" type="tns:Holidays"></element>
    		<element name="SubConfigurations" type="tns:Configuration" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="hierarchy" type="string"></attribute>
    </complexType>

    <complexType name="Fixed">
    	<attribute name="month" type="tns:Month"></attribute>
    	<attribute name="day">
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="1"></minInclusive>
    				<maxInclusive value="31"></maxInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>


    <simpleType name="When">
    	<restriction base="string">
    		<enumeration value="BEFORE"></enumeration>
    		<enumeration value="AFTER"></enumeration>
    	</restriction>
    </simpleType>
</schema>

=== svendiedrichsen/jollyday/tags/v_0_4_5/jollyday.old/src/main/resources/holidays/Holidays_br.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="br" description="Brazil"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="APRIL" day="21" descriptionPropertiesKey="TIRADENTES"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="SEPTEMBER" day="7" descriptionPropertiesKey="INDEPENDENCE"/>
		<tns:Fixed month="OCTOBER" day="12" validFrom="1980" descriptionPropertiesKey="APARECIDA"/>
		<tns:Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS"/>
		<tns:Fixed month="NOVEMBER" day="15" descriptionPropertiesKey="NATIONAL_DAY"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="CARNIVAL"/>
		<tns:ChristianHoliday type="ASH_WEDNESDAY"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY"/>
		<tns:ChristianHoliday type="CORPUS_CHRISTI"/>
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="rj" description="Rio de Janeiro">
		<tns:Holidays>
			<tns:Fixed month="APRIL" day="23" validFrom="2007" descriptionPropertiesKey="ST_GEORGE"/>
			<tns:Fixed month="NOVEMBER" day="20" descriptionPropertiesKey="BLACK_AWARENESS"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="crj" description="City of Rio de Janeiro">
			<tns:Holidays>
				<tns:Fixed month="JANUARY" day="20" descriptionPropertiesKey="ST_SEBASTIAN"/>
				<tns:Fixed month="APRIL" day="23" validTo="2006" descriptionPropertiesKey="ST_GEORGE"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="s" description="Sao Paulo">
		<tns:Holidays>
			<tns:Fixed month="JULY" day="9" descriptionPropertiesKey="CONST_REVOLUTION"/>
			<tns:Fixed month="NOVEMBER" day="20" descriptionPropertiesKey="BLACK_AWARENESS"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="cs" description="City of Sao Paulo">
			<tns:Holidays>
				<tns:Fixed month="JANUARY" day="25" descriptionPropertiesKey="FOUNDATION"/>
				<tns:Fixed month="NOVEMBER" day="4" descriptionPropertiesKey="FOUNDATION"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="mg" description="Minas Gerais">
		<tns:Holidays></tns:Holidays>
		<tns:SubConfigurations hierarchy="bh" description="Belo Horizonte">
			<tns:Holidays>
				<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="LADY_GOOD_VOYAGE"/>
				<tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="LADY_CONCEICAO"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="ms" description="Mato Grosso do Sul">
		<tns:Holidays>
			<tns:Fixed month="OCTOBER" day="11" descriptionPropertiesKey="FOUNDATION"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="cg" description="Campo Grande">
			<tns:Holidays>
				<tns:Fixed month="AUGUST" day="26" descriptionPropertiesKey="FOUNDATION"/>
			</tns:Holidays>
		</tns:SubConfigurations>
		<tns:SubConfigurations hierarchy="do" description="Dourados">
			<tns:Holidays>
				<tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="LADY_CONCEICAO"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="pr" description="Parana">
		<tns:Holidays></tns:Holidays>
		<tns:SubConfigurations hierarchy="cu" description="Curitiba">
			<tns:Holidays>
				<tns:Fixed month="SEPTEMBER" day="8" descriptionPropertiesKey="LADY_LIGHT_PINE"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="rs" description="Rio Grande do Sul">
		<tns:Holidays>
			<tns:Fixed month="SEPTEMBER" day="20" descriptionPropertiesKey="FARROUS_REVOLUTION"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="sm" description="Santa Maria">
			<tns:Holidays>
				<tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="LADY_CONCEICAO"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="rn" description="Rio Grande do Norte">
		<tns:Holidays>
			<tns:Fixed month="OCTOBER" day="3" descriptionPropertiesKey="MARTYRS_DAY"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="na" description="Natal">
			<tns:Holidays>
				<tns:Fixed month="NOVEMBER" day="21" descriptionPropertiesKey="LADY_APRESENTACAO"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="go" description="GoiÃ¡s">
		<tns:Holidays>
			<tns:Fixed month="OCTOBER" day="24" descriptionPropertiesKey="FOUNDATION"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="pe" description="Pernambuco">
		<tns:Holidays>
			<tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="LADY_CONCEICAO"/>
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_at.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="at" description="Austria"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="holiday.description.NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="holiday.description.EPIPHANY"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="holiday.description.LABOUR_DAY"/>
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="holiday.description.ASSUMPTION_DAY"/>
		<tns:Fixed month="OCTOBER" day="26" descriptionPropertiesKey="holiday.description.NATIONAL_DAY"/>
		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="holiday.description.ALL_SAINTS"/>
		<tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="holiday.description.IMMACULATE_CONCEPTION"/>
		<tns:Fixed month="DECEMBER" day="24" descriptionPropertiesKey="holiday.description.CHRISTMAS_EVE"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="holiday.description.CHRISTMAS"/>
		<tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="holiday.description.STEPHENS"/>
		<tns:Fixed month="DECEMBER" day="31" descriptionPropertiesKey="holiday.description.NEW_YEARS_EVE"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
		<tns:ChristianHoliday type="ASCENSION_DAY" />
		<tns:ChristianHoliday type="WHIT_MONDAY" />
		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="b" description="Burgenland">
		<tns:Holidays>
			<tns:Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="holiday.description.MARTINS_TAG"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="k" description="Kärnten">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19" descriptionPropertiesKey="holiday.description.JOSEFS_DAY"/>
			<tns:Fixed month="OCTOBER" day="10" descriptionPropertiesKey="holiday.description.PLEBISCITE"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="nö" description="Niederösterreich">
		<tns:Holidays>
			<tns:Fixed month="NOVEMBER" day="15" descriptionPropertiesKey="holiday.description.LEOPOLD"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="oö" description="Oberösterreich">
		<tns:Holidays>
			<tns:Fixed month="MAY" day="4" descriptionPropertiesKey="holiday.description.FLORIAN"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="s" description="Salzburg">
		<tns:Holidays>
			<tns:Fixed month="SEPTEMBER" day="24" descriptionPropertiesKey="holiday.description.RUPERT"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="st" description="Steiermark">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19" descriptionPropertiesKey="holiday.description.JOSEFS_DAY"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="t" description="Tirol">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19" descriptionPropertiesKey="holiday.description.JOSEFS_DAY"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="va" description="Vorarlberg">
		<tns:Holidays>
			<tns:Fixed month="MARCH" day="19" descriptionPropertiesKey="holiday.description.JOSEFS_DAY"/>
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="w" description="Wien">
		<tns:Holidays>
			<tns:Fixed month="NOVEMBER" day="15" descriptionPropertiesKey="holiday.description.LEOPOLD"/>
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_sk.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="sk" description="Slovakia"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="6" />
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="MAY" day="8" />
		<tns:Fixed month="JULY" day="5" />
		<tns:Fixed month="AUGUST" day="29" />
		<tns:Fixed month="SEPTEMBER" day="1" />
		<tns:Fixed month="SEPTEMBER" day="15" />
		<tns:Fixed month="NOVEMBER" day="1" />
		<tns:Fixed month="NOVEMBER" day="17" />
		<tns:Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="DECEMBER" day="26" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_kz.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="kz" description="Kazakhstan"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="MARCH" day="8" descriptionPropertiesKey="INTERNATIONAL_WOMAN"/>
		<tns:Fixed month="MARCH" day="22" descriptionPropertiesKey="SPRING_DAY"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="VICTORY"/>
		<tns:Fixed month="JULY" day="6" descriptionPropertiesKey="REPUBLIC_DAY"/>
		<tns:Fixed month="AUGUST" day="30" descriptionPropertiesKey="CONSTITUTION_DAY"/>
		<tns:Fixed month="DECEMBER" day="16" descriptionPropertiesKey="INDEPENDENCE"/>
		<tns:IslamicHoliday type="ID_UL_ADHA"/>
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_ba.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ba" description="Bosnia and Herzegovina" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
	  <tns:Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:Fixed month="JANUARY" day="14" descriptionPropertiesKey="NEW_YEAR"/>
	  <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="MAY_DAY"/>
	  <tns:Fixed month="MAY" day="6" descriptionPropertiesKey="ST_GEORGE" />
	  <tns:Fixed month="JUNE" day="28" descriptionPropertiesKey="ST_VITUS"/>
	  <tns:Fixed month="JULY" day="12" descriptionPropertiesKey="ST_PETER"/>
	  <tns:Fixed month="AUGUST" day="2" descriptionPropertiesKey="ST_ELIJAH"/>
	  <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
	  <tns:Fixed month="AUGUST" day="28" descriptionPropertiesKey="ASSUMPTION_DAY"/>
	  <tns:Fixed month="SEPTEMBER" day="8" descriptionPropertiesKey="NATIVITY_MARY"/>
	  <tns:Fixed month="SEPTEMBER" day="21" descriptionPropertiesKey="NATIVITY_MARY"/>
	  <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
	  <tns:Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS"/>
	  <tns:Fixed month="NOVEMBER" day="8" descriptionPropertiesKey="ST_DEMETRIUS"/>
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:IslamicHoliday type="ID_AL_FITR"/>
	  <tns:IslamicHoliday type="ID_UL_ADHA"/>
	  <tns:IslamicHoliday type="MAWLID_AN_NABI"/>
  </tns:Holidays>
  <tns:SubConfigurations hierarchy="rs" description="Republika Srpska">
  	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="9" descriptionPropertiesKey="REPUBLIC_DAY"/>
		<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="VICTORY"/>
		<tns:Fixed month="NOVEMBER" day="21" descriptionPropertiesKey="DAYTON"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="fbh" description="Federation of Bosnia and Herzegovina">
  	<tns:Holidays>
		<tns:Fixed month="MARCH" day="1" descriptionPropertiesKey="INDEPENDENCE"/>
		<tns:Fixed month="NOVEMBER" day="25" descriptionPropertiesKey="NATIONAL_DAY"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_cz.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="cz" description="Czech Republic" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="MAY" day="8"/>
	  <tns:Fixed month="JULY" day="5"/>
	  <tns:Fixed month="JULY" day="6"/>
	  <tns:Fixed month="SEPTEMBER" day="28"/>
	  <tns:Fixed month="OCTOBER" day="28"/>
	  <tns:Fixed month="NOVEMBER" day="17"/>
	  <tns:Fixed month="DECEMBER" day="24"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:Fixed month="DECEMBER" day="26"/>
	  <tns:RelativeToEastern days="1"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_pe.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="pe" description="Peru"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
	  <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
	  <tns:Fixed month="JUNE" day="29" descriptionPropertiesKey="ST_PETER_PAUL"/>
	  <tns:Fixed month="JULY" day="28" descriptionPropertiesKey="INDEPENDENCE"/>
	  <tns:Fixed month="JULY" day="29" descriptionPropertiesKey="INDEPENDENCE"/>
	  <tns:Fixed month="AUGUST" day="30" descriptionPropertiesKey="SANTA_ROSA"/>
	  <tns:Fixed month="OCTOBER" day="8" descriptionPropertiesKey="ANGAMOS"/>
	  <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
	  <tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="IMMACULATE_CONCEPTION"/>
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
      <tns:ChristianHoliday type="EASTER" />
	  <tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
	  <tns:ChristianHoliday type="GOOD_FRIDAY"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/tags/v_0_4_6/src/main/resources/holidays/Holidays_de.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="de" description="Germany" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
	  <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
	  <tns:Fixed month="JUNE" day="17" validFrom="1954" validTo="1990" descriptionPropertiesKey="UNIFICATION"/>
	  <tns:Fixed month="OCTOBER" day="3" validFrom="1990"  descriptionPropertiesKey="UNIFICATION"/>
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
      <tns:ChristianHoliday type="EASTER" />
	  <tns:ChristianHoliday type="GOOD_FRIDAY"/>
	  <tns:ChristianHoliday type="EASTER_MONDAY"/>
	  <tns:ChristianHoliday type="ASCENSION_DAY"/>
	  <tns:ChristianHoliday type="WHIT_SUNDAY" />
	  <tns:ChristianHoliday type="WHIT_MONDAY" />
  </tns:Holidays>
  <tns:SubConfigurations hierarchy="bb" description="Brandenburg">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="bw" description="Baden-Württenberg">
  	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
  		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="by" description="Bayern">
  	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
  		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  	</tns:Holidays>
  	<tns:SubConfigurations hierarchy="mu" description="Munich">
  		<tns:Holidays>
  			<tns:Fixed day="15" month="AUGUST" descriptionPropertiesKey="ASSUMPTION_DAY"/>
  		</tns:Holidays>
  	</tns:SubConfigurations>
  	<tns:SubConfigurations hierarchy="ag" description="Augsburg">
  		<tns:Holidays>
  			<tns:Fixed day="8" month="AUGUST" descriptionPropertiesKey="PEACE"/>
  			<tns:Fixed day="15" month="AUGUST" descriptionPropertiesKey="ASSUMPTION_DAY"/>
  		</tns:Holidays>
  	</tns:SubConfigurations>
  	<tns:SubConfigurations hierarchy="wu" description="Würzburg">
  		<tns:Holidays>
  			<tns:Fixed day="15" month="AUGUST" descriptionPropertiesKey="ASSUMPTION_DAY"/>
  		</tns:Holidays>
  	</tns:SubConfigurations>
  	<tns:SubConfigurations hierarchy="re" description="Regensburg">
  		<tns:Holidays>
  			<tns:Fixed day="15" month="AUGUST" descriptionPropertiesKey="ASSUMPTION_DAY"/>
  		</tns:Holidays>
  	</tns:SubConfigurations>
  	<tns:SubConfigurations hierarchy="in" description="Ingolstadt">
  		<tns:Holidays>
  			<tns:Fixed day="15" month="AUGUST" descriptionPropertiesKey="ASSUMPTION_DAY"/>
  		</tns:Holidays>
  	</tns:SubConfigurations>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="he" description="Hessen">
  	<tns:Holidays>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="mv" description="Mecklenburg-Vorpommern">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="nw" description="Nordrhein-Westfalen">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="rp" description="Rheinland-Pfalz">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sl" description="Saarland">
  	<tns:Holidays>
  		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
  		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sn" description="Sachsen">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
  		<tns:RelativeToFixed descriptionPropertiesKey="REPENTANCE_PRAYER">
  			<tns:Weekday>WEDNESDAY</tns:Weekday>
  			<tns:When>BEFORE</tns:When>
  			<tns:Date month="NOVEMBER" day="23"/>
  		</tns:RelativeToFixed>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="st" description="Sachsen-Anhalt">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
  		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="th" description="Thüringen">
  	<tns:Holidays>
  		<tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
</tns:Configuration>
