=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://jollyday.sourceforge.net/Jollyday"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:jolly="http://jollyday.sourceforge.net/Jollyday">

	<simpleType name="Weekday">
		<restriction base="string">
			<enumeration value="MONDAY"></enumeration>
			<enumeration value="TUESDAY"></enumeration>
			<enumeration value="WEDNESDAY"></enumeration>
			<enumeration value="THURSDAY"></enumeration>
			<enumeration value="FRIDAY"></enumeration>
			<enumeration value="SATURDAY"></enumeration>
			<enumeration value="SUNDAY"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="Month">
		<restriction base="string">
			<enumeration value="JANUARY"></enumeration>
			<enumeration value="FEBRUARY"></enumeration>
			<enumeration value="MARCH"></enumeration>
			<enumeration value="MAY"></enumeration>
			<enumeration value="JUNE"></enumeration>
			<enumeration value="JULY"></enumeration>
			<enumeration value="AUGUST"></enumeration>
			<enumeration value="SEPTEMBER"></enumeration>
			<enumeration value="OCTOBER"></enumeration>
			<enumeration value="NOVEMBER"></enumeration>
			<enumeration value="DECEMBER"></enumeration>
			<enumeration value="APRIL"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="CycleType">
		<annotation>
			<appinfo>
				<typesafeEnumClass map="true" />
			</appinfo>
		</annotation>
		<restriction base="string">
			<enumeration value="EVERY_YEAR"></enumeration>
			<enumeration value="TWO_YEARS"></enumeration>
			<enumeration value="THREE_YEARS"></enumeration>
			<enumeration value="FOUR_YEARS"></enumeration>
			<enumeration value="FIVE_YEARS"></enumeration>
			<enumeration value="SIX_YEARS"></enumeration>
			<enumeration value="SEVEN_YEARS"></enumeration>
			<enumeration value="ODD_YEARS"></enumeration>
			<enumeration value="EVEN_YEARS"></enumeration>
		</restriction>
	</simpleType>

	<element name="Configuration" type="jolly:Configuration"></element>

	<complexType name="Configuration">
		<sequence>
			<element name="Holiday" type="jolly:HolidayRule" maxOccurs="unbounded"
				minOccurs="0"></element>
			<element name="SubConfigurations" type="jolly:Configuration"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="hierarchy" type="string"></attribute>
		<attribute name="description" type="string"></attribute>
	</complexType>

	<complexType name="Fixed">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="month" type="jolly:Month"></attribute>

				<attribute name="day">
					<simpleType>
						<restriction base="int">
							<minInclusive value="1"></minInclusive>
							<maxInclusive value="31"></maxInclusive>
						</restriction>
					</simpleType>
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="When">
		<restriction base="string">
			<enumeration value="BEFORE"></enumeration>
			<enumeration value="AFTER"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="FixedWeekdayInMonth">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="which" type="jolly:Which"></attribute>

				<attribute name="weekday" type="jolly:Weekday"></attribute>

				<attribute name="month" type="jolly:Month"></attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="Which">
		<restriction base="string">
			<enumeration value="FIRST"></enumeration>
			<enumeration value="SECOND"></enumeration>
			<enumeration value="THIRD"></enumeration>
			<enumeration value="LAST"></enumeration>
			<enumeration value="FOURTH"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="IslamicHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:IslamicHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="IslamicHolidayType">
		<restriction base="string">
			<enumeration value="NEWYEAR"></enumeration>
			<enumeration value="ASCHURA"></enumeration>
			<enumeration value="MAWLID_AN_NABI"></enumeration>
			<enumeration value="LAILAT_AL_MIRAJ"></enumeration>
			<enumeration value="LAILAT_AL_BARAT"></enumeration>
			<enumeration value="RAMADAN"></enumeration>
			<enumeration value="LAILAT_AL_QADR"></enumeration>
			<enumeration value="ID_AL_FITR"></enumeration>
			<enumeration value="ID_UL_ADHA"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="ChronologyType">
		<restriction base="string">
			<enumeration value="JULIAN"></enumeration>
			<enumeration value="GREGORIAN"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="ChristianHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:ChristianHolidayType">
				</attribute>

				<attribute name="chronology" type="jolly:ChronologyType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="HolidayType">
		<restriction base="string">
			<enumeration value="OFFICIAL_HOLIDAY" />
			<enumeration value="UNOFFICIAL_HOLIDAY" />
		</restriction>
	</simpleType>

	<simpleType name="ChristianHolidayType">
		<restriction base="string">
			<enumeration value="GOOD_FRIDAY"></enumeration>
			<enumeration value="EASTER_MONDAY"></enumeration>
			<enumeration value="ASCENSION_DAY"></enumeration>
			<enumeration value="WHIT_MONDAY"></enumeration>
			<enumeration value="CORPUS_CHRISTI"></enumeration>
			<enumeration value="MAUNDY_THURSDAY"></enumeration>
			<enumeration value="ASH_WEDNESDAY"></enumeration>
			<enumeration value="MARDI_GRAS"></enumeration>
			<enumeration value="GENERAL_PRAYER_DAY"></enumeration>
			<enumeration value="CLEAN_MONDAY"></enumeration>
			<enumeration value="SHROVE_MONDAY"></enumeration>
			<enumeration value="PENTECOST"></enumeration>
			<enumeration value="CARNIVAL"></enumeration>
			<enumeration value="EASTER_SATURDAY"></enumeration>
			<enumeration value="EASTER_TUESDAY"></enumeration>
			<enumeration value="SACRED_HEART"></enumeration>
			<enumeration value="EASTER"></enumeration>
			<enumeration value="PENTECOST_MONDAY"></enumeration>
			<enumeration value="WHIT_SUNDAY"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="Holiday" abstract="true">
		<attribute name="descriptionPropertiesKey" type="string" />
		<attribute name="localizedType" type="jolly:HolidayType"
			default="OFFICIAL_HOLIDAY" />
	</complexType>


	<simpleType name="To">
		<restriction base="string">
			<enumeration value="NEXT"></enumeration>
			<enumeration value="PREVIOUS"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="MovingCondition">
		<sequence>
			<element name="when" type="jolly:Weekday" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="to" type="jolly:To"></attribute>
		<attribute name="weekday" type="jolly:Weekday"></attribute>
	</complexType>

	<simpleType name="HinduHolidayType">
		<restriction base="string">
			<enumeration value="HOLI"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="HinduHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:HinduHolidayType"></attribute>
			</extension>
		</complexContent>
	</complexType>





	<simpleType name="HebrewHolidayType">
		<restriction base="string">
			<enumeration value="ROSH_HASHANAH"></enumeration>
			<enumeration value="ASERET_YEMEI_TESHUVA"></enumeration>
			<enumeration value="YOM_KIPPUR"></enumeration>
			<enumeration value="SUKKOT"></enumeration>
			<enumeration value="SHEMINI_ATZERET"></enumeration>
			<enumeration value="HANUKKAH"></enumeration>
			<enumeration value="ASARAH_BETEVET"></enumeration>
			<enumeration value="TU_BISHVAT"></enumeration>
			<enumeration value="PURIM"></enumeration>
			<enumeration value="1_NISAN"></enumeration>
			<enumeration value="PESACH"></enumeration>
			<enumeration value="SEFIRAH"></enumeration>
			<enumeration value="LAG_BAOMER"></enumeration>
			<enumeration value="SHAVOUT"></enumeration>
			<enumeration value="17_TAMMUZ"></enumeration>
			<enumeration value="TISHA_BAV"></enumeration>
			<enumeration value="1_ELUL"></enumeration>
			<enumeration value="ROSH_CODESH"></enumeration>
			<enumeration value="SHABBAT"></enumeration>
			<enumeration value="YOM_HASHOAH"></enumeration>
			<enumeration value="YOM_HAZIKARON"></enumeration>
			<enumeration value="YOM_HAATZAMAUT"></enumeration>
			<enumeration value="YOM_YERUSHALAIM"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="EthiopianOrthodoxHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:EthiopianOrthodoxHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="EthiopianOrthodoxHolidayType">
		<restriction base="string">
			<enumeration value="TIMKAT"></enumeration>
			<enumeration value="ENKUTATASH"></enumeration>
			<enumeration value="MESKEL"></enumeration>
		</restriction>
	</simpleType>



	<complexType name="RelativeToEasterSunday">
		<complexContent>
			<extension base="jolly:Holiday">
				<sequence>
					<element name="chronology" type="jolly:ChronologyType">
					</element>
					<element name="days" type="int"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="HolidayRule">
		<sequence>
			<choice>
				<element name="Fixed" type="jolly:Fixed"></element>
				<element name="FixedWeekdayInMonth" type="jolly:FixedWeekdayInMonth">
				</element>
				<element name="RelativeToEasterSunday" type="jolly:RelativeToEasterSunday">
				</element>
				<element name="IslamicHoliday" type="jolly:IslamicHoliday"></element>
				<element name="HinduHoliday" type="jolly:HinduHoliday"></element>
				<element name="EthiopianOrthodoxHoliday" type="jolly:EthiopianOrthodoxHoliday">
				</element>
				<element name="ChristianHoliday" type="jolly:ChristianHoliday">
				</element>
			</choice>
			<sequence>
				<element name="MovingCondition" type="jolly:MovingCondition"
					minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</sequence>

		<attribute name="id" type="string"></attribute>
		<attribute name="validFrom" type="int"></attribute>
		<attribute name="validTo" type="int"></attribute>
		<attribute name="every" type="jolly:CycleType" default="EVERY_YEAR"></attribute>
	</complexType>

	<complexType name="HolidayRuleRef">
		<attribute name="ref" type="string"></attribute>
	</complexType>

</schema>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_pl.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="pl" description="Poland"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="MAY" day="3" />
		<tns:Fixed month="AUGUST" day="15" />
		<tns:Fixed month="NOVEMBER" day="1" />
		<tns:Fixed month="NOVEMBER" day="11" />
		<tns:Fixed month="DECEMBER" day="25" />
		<tns:Fixed month="DECEMBER" day="26" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/test/resources/holidays/Holidays_test_fr_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="fr" description="France"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../../../main/resources/Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="8" descriptionPropertiesKey="VICTORY_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JULY" day="14" descriptionPropertiesKey="NATIONAL_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_MARY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="1"
			descriptionPropertiesKey="ALL_SAINTS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="11"
			descriptionPropertiesKey="REMEMBRANCE" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="APRIL" day="5" descriptionPropertiesKey="EASTER_MONDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="13" descriptionPropertiesKey="ASCENSION_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="24" descriptionPropertiesKey="WHIT_MONDAY" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="ma"
		description="Martinique">
		<tns:Holiday>
			<tns:Fixed month="MAY" day="22" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="gu"
		description="Guadeloupe">
		<tns:Holiday>
			<tns:Fixed month="MAY" day="27" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="gy"
		description="Guyane">
		<tns:Holiday>
			<tns:Fixed month="JUNE" day="10" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="lr"
		description="La Reunion">
		<tns:Holiday>
			<tns:Fixed month="DECEMBER" day="20" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="br"
		description="Bas-Rhin">
		<tns:Holiday>
			<tns:Fixed month="DECEMBER" day="26" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:ChristianHoliday type="GOOD_FRIDAY" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="hr"
		description="Haut-Rhin">
		<tns:Holiday>
			<tns:Fixed month="DECEMBER" day="26" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:ChristianHoliday type="GOOD_FRIDAY" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="mo"
		description="Moselle">
		<tns:Holiday>
			<tns:Fixed month="DECEMBER" day="26" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_es.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="es" description="Spain" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="JANUARY" day="6"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="OCTOBER" day="12"/>
	  <tns:Fixed month="NOVEMBER" day="1"/>
	  <tns:Fixed month="DECEMBER" day="6" validFrom="1978"/>
	  <tns:Fixed month="DECEMBER" day="8"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:ChristianHoliday type="GOOD_FRIDAY"/>
  </tns:Holidays>
  <tns:SubConfigurations hierarchy="an" description="Andalucia">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="1"/>
  		<tns:Fixed month="FEBRUARY" day="28"/>
  		<tns:FixedMoving month="AUGUST" day="15" substituted="ON_WEEKEND" with="NEXT" weekday="MONDAY"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="ar" description="Aragon">
  	<tns:Holidays>
  		<tns:Fixed month="APRIL" day="23"/>
  		<tns:FixedMoving month="AUGUST" day="15" substituted="ON_WEEKEND" with="NEXT" weekday="MONDAY"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="ce" description="Ceuta">
  	<tns:Holidays>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:Fixed month="SEPTEMBER" day="2"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  		<tns:IslamicHoliday type="ID_UL_ADHA" validFrom="2010"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="ml" description="Melilla">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  		<tns:IslamicHoliday type="ID_UL_ADHA" validFrom="2010"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="cl" description="Castile and Leon">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
  		<tns:Fixed month="APRIL" day="23"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="cm" description="Castile - La Mancha">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
  		<tns:Fixed month="MAY" day="31"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="cn" description="Canary Islands">
  	<tns:Holidays>
  		<tns:Fixed month="MAY" day="31"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="ct" description="Catalonia">
  	<tns:Holidays>
  		<tns:Fixed month="JUNE" day="24"/>
  		<tns:Fixed month="SEPTEMBER" day="11"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="EASTER_MONDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="ex" description="Extremadura">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:Fixed month="SEPTEMBER" day="8"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="ga" description="Galicia">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
  		<tns:Fixed month="MAY" day="17"/>
  		<tns:Fixed month="JULY" day="25"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="ib" description="Balearic Island">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="1"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="EASTER_MONDAY"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="lo" description="La Rioja">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
  		<tns:Fixed month="JUNE" day="9"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="m" description="Madrid">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
  		<tns:Fixed month="MAY" day="15"/>
		<tns:Fixed month="AUGUST" day="15"/>
		<tns:Fixed month="NOVEMBER" day="9"/>
  		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="mu" description="Murcia">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
  		<tns:Fixed month="JUNE" day="9"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="na" description="Navarre">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  		<tns:ChristianHoliday type="EASTER_MONDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="o" description="Asturias">
  	<tns:Holidays>
  		<tns:Fixed month="SEPTEMBER" day="8"/>
  		<tns:FixedMoving month="AUGUST" day="15" substituted="ON_WEEKEND" with="NEXT" weekday="MONDAY"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="pv" description="Euskadi">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:Fixed month="OCTOBER" day="25"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  		<tns:ChristianHoliday type="EASTER_MONDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="s" description="Cantabria">
  	<tns:Holidays>
  		<tns:Fixed month="JULY" day="28"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:Fixed month="SEPTEMBER" day="15"/>
  		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
 <tns:SubConfigurations hierarchy="vc" description="Valencia">
  	<tns:Holidays>
  		<tns:Fixed month="MARCH" day="19"/>
		<tns:Fixed month="AUGUST" day="15"/>
  		<tns:Fixed month="OCTOBER" day="9"/>
  		<tns:ChristianHoliday type="EASTER_MONDAY"/>
  	</tns:Holidays>
 </tns:SubConfigurations>
</tns:Configuration>
