=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://jollyday.sourceforge.net/Jollyday"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:jolly="http://jollyday.sourceforge.net/Jollyday">

	<simpleType name="Weekday">
		<restriction base="string">
			<enumeration value="MONDAY"></enumeration>
			<enumeration value="TUESDAY"></enumeration>
			<enumeration value="WEDNESDAY"></enumeration>
			<enumeration value="THURSDAY"></enumeration>
			<enumeration value="FRIDAY"></enumeration>
			<enumeration value="SATURDAY"></enumeration>
			<enumeration value="SUNDAY"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="Month">
		<restriction base="string">
			<enumeration value="JANUARY"></enumeration>
			<enumeration value="FEBRUARY"></enumeration>
			<enumeration value="MARCH"></enumeration>
			<enumeration value="MAY"></enumeration>
			<enumeration value="JUNE"></enumeration>
			<enumeration value="JULY"></enumeration>
			<enumeration value="AUGUST"></enumeration>
			<enumeration value="SEPTEMBER"></enumeration>
			<enumeration value="OCTOBER"></enumeration>
			<enumeration value="NOVEMBER"></enumeration>
			<enumeration value="DECEMBER"></enumeration>
			<enumeration value="APRIL"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="CycleType">
		<annotation>
			<appinfo>
				<typesafeEnumClass map="true" />
			</appinfo>
		</annotation>
		<restriction base="string">
			<enumeration value="EVERY_YEAR"></enumeration>
			<enumeration value="TWO_YEARS"></enumeration>
			<enumeration value="THREE_YEARS"></enumeration>
			<enumeration value="FOUR_YEARS"></enumeration>
			<enumeration value="FIVE_YEARS"></enumeration>
			<enumeration value="SIX_YEARS"></enumeration>
			<enumeration value="SEVEN_YEARS"></enumeration>
			<enumeration value="ODD_YEARS"></enumeration>
			<enumeration value="EVEN_YEARS"></enumeration>
		</restriction>
	</simpleType>

	<element name="Configuration" type="jolly:Configuration"></element>

	<complexType name="Configuration">
		<sequence>
			<element name="Holiday" type="jolly:HolidayRule" maxOccurs="unbounded"
				minOccurs="0"></element>
			<element name="SubConfigurations" type="jolly:Configuration"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="hierarchy" type="string"></attribute>
		<attribute name="description" type="string"></attribute>
	</complexType>

	<complexType name="Fixed">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="month" type="jolly:Month"></attribute>

				<attribute name="day">
					<simpleType>
						<restriction base="int">
							<minInclusive value="1"></minInclusive>
							<maxInclusive value="31"></maxInclusive>
						</restriction>
					</simpleType>
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="When">
		<restriction base="string">
			<enumeration value="BEFORE"></enumeration>
			<enumeration value="AFTER"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="FixedWeekdayInMonth">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="which" type="jolly:Which"></attribute>

				<attribute name="weekday" type="jolly:Weekday"></attribute>

				<attribute name="month" type="jolly:Month"></attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="Which">
		<restriction base="string">
			<enumeration value="FIRST"></enumeration>
			<enumeration value="SECOND"></enumeration>
			<enumeration value="THIRD"></enumeration>
			<enumeration value="LAST"></enumeration>
			<enumeration value="FOURTH"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="IslamicHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:IslamicHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="IslamicHolidayType">
		<restriction base="string">
			<enumeration value="NEWYEAR"></enumeration>
			<enumeration value="ASCHURA"></enumeration>
			<enumeration value="MAWLID_AN_NABI"></enumeration>
			<enumeration value="LAILAT_AL_MIRAJ"></enumeration>
			<enumeration value="LAILAT_AL_BARAT"></enumeration>
			<enumeration value="RAMADAN"></enumeration>
			<enumeration value="LAILAT_AL_QADR"></enumeration>
			<enumeration value="ID_AL_FITR"></enumeration>
			<enumeration value="ID_UL_ADHA"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="ChronologyType">
		<restriction base="string">
			<enumeration value="JULIAN"></enumeration>
			<enumeration value="GREGORIAN"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="ChristianHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:ChristianHolidayType">
				</attribute>

				<attribute name="chronology" type="jolly:ChronologyType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="HolidayType">
		<restriction base="string">
			<enumeration value="OFFICIAL_HOLIDAY" />
			<enumeration value="UNOFFICIAL_HOLIDAY" />
		</restriction>
	</simpleType>

	<simpleType name="ChristianHolidayType">
		<restriction base="string">
			<enumeration value="GOOD_FRIDAY"></enumeration>
			<enumeration value="EASTER_MONDAY"></enumeration>
			<enumeration value="ASCENSION_DAY"></enumeration>
			<enumeration value="WHIT_MONDAY"></enumeration>
			<enumeration value="CORPUS_CHRISTI"></enumeration>
			<enumeration value="MAUNDY_THURSDAY"></enumeration>
			<enumeration value="ASH_WEDNESDAY"></enumeration>
			<enumeration value="MARDI_GRAS"></enumeration>
			<enumeration value="GENERAL_PRAYER_DAY"></enumeration>
			<enumeration value="CLEAN_MONDAY"></enumeration>
			<enumeration value="SHROVE_MONDAY"></enumeration>
			<enumeration value="PENTECOST"></enumeration>
			<enumeration value="CARNIVAL"></enumeration>
			<enumeration value="EASTER_SATURDAY"></enumeration>
			<enumeration value="EASTER_TUESDAY"></enumeration>
			<enumeration value="SACRED_HEART"></enumeration>
			<enumeration value="EASTER"></enumeration>
			<enumeration value="PENTECOST_MONDAY"></enumeration>
			<enumeration value="WHIT_SUNDAY"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="Holiday" abstract="true">
		<attribute name="descriptionPropertiesKey" type="string" />
		<attribute name="localizedType" type="jolly:HolidayType"
			default="OFFICIAL_HOLIDAY" />
	</complexType>


	<simpleType name="To">
		<restriction base="string">
			<enumeration value="NEXT"></enumeration>
			<enumeration value="PREVIOUS"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="MovingCondition">
		<sequence>
			<element name="when" type="jolly:Weekday" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="to" type="jolly:To"></attribute>
		<attribute name="weekday" type="jolly:Weekday"></attribute>
	</complexType>

	<simpleType name="HinduHolidayType">
		<restriction base="string">
			<enumeration value="HOLI"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="HinduHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:HinduHolidayType"></attribute>
			</extension>
		</complexContent>
	</complexType>





	<simpleType name="HebrewHolidayType">
		<restriction base="string">
			<enumeration value="ROSH_HASHANAH"></enumeration>
			<enumeration value="ASERET_YEMEI_TESHUVA"></enumeration>
			<enumeration value="YOM_KIPPUR"></enumeration>
			<enumeration value="SUKKOT"></enumeration>
			<enumeration value="SHEMINI_ATZERET"></enumeration>
			<enumeration value="HANUKKAH"></enumeration>
			<enumeration value="ASARAH_BETEVET"></enumeration>
			<enumeration value="TU_BISHVAT"></enumeration>
			<enumeration value="PURIM"></enumeration>
			<enumeration value="1_NISAN"></enumeration>
			<enumeration value="PESACH"></enumeration>
			<enumeration value="SEFIRAH"></enumeration>
			<enumeration value="LAG_BAOMER"></enumeration>
			<enumeration value="SHAVOUT"></enumeration>
			<enumeration value="17_TAMMUZ"></enumeration>
			<enumeration value="TISHA_BAV"></enumeration>
			<enumeration value="1_ELUL"></enumeration>
			<enumeration value="ROSH_CODESH"></enumeration>
			<enumeration value="SHABBAT"></enumeration>
			<enumeration value="YOM_HASHOAH"></enumeration>
			<enumeration value="YOM_HAZIKARON"></enumeration>
			<enumeration value="YOM_HAATZAMAUT"></enumeration>
			<enumeration value="YOM_YERUSHALAIM"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="EthiopianOrthodoxHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:EthiopianOrthodoxHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="EthiopianOrthodoxHolidayType">
		<restriction base="string">
			<enumeration value="TIMKAT"></enumeration>
			<enumeration value="ENKUTATASH"></enumeration>
			<enumeration value="MESKEL"></enumeration>
		</restriction>
	</simpleType>



	<complexType name="RelativeToEasterSunday">
		<complexContent>
			<extension base="jolly:Holiday">
				<sequence>
					<element name="chronology" type="jolly:ChronologyType">
					</element>
					<element name="days" type="int"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="HolidayRule">
		<sequence>
			<choice>
				<element name="Fixed" type="jolly:Fixed"></element>
				<element name="FixedWeekdayInMonth" type="jolly:FixedWeekdayInMonth">
				</element>
				<element name="RelativeToEasterSunday" type="jolly:RelativeToEasterSunday">
				</element>
				<element name="IslamicHoliday" type="jolly:IslamicHoliday"></element>
				<element name="HinduHoliday" type="jolly:HinduHoliday"></element>
				<element name="EthiopianOrthodoxHoliday" type="jolly:EthiopianOrthodoxHoliday">
				</element>
				<element name="ChristianHoliday" type="jolly:ChristianHoliday">
				</element>
			</choice>
			<sequence>
				<element name="MovingCondition" type="jolly:MovingCondition"
					minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</sequence>

		<attribute name="id" type="string"></attribute>
		<attribute name="validFrom" type="int"></attribute>
		<attribute name="validTo" type="int"></attribute>
		<attribute name="every" type="jolly:CycleType" default="EVERY_YEAR"></attribute>
	</complexType>

	<complexType name="HolidayRuleRef">
		<attribute name="ref" type="string"></attribute>
	</complexType>

</schema>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_ba.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ba" description="Bosnia and Herzegovina"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="14"
			descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="MAY_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="6" descriptionPropertiesKey="ST_GEORGE" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JUNE" day="28" descriptionPropertiesKey="ST_VITUS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JULY" day="12" descriptionPropertiesKey="ST_PETER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="2" descriptionPropertiesKey="ST_ELIJAH" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="28" descriptionPropertiesKey="ASSUMPTION_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="SEPTEMBER" day="8"
			descriptionPropertiesKey="NATIVITY_MARY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="SEPTEMBER" day="21"
			descriptionPropertiesKey="NATIVITY_MARY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="1"
			descriptionPropertiesKey="ALL_SAINTS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="2"
			descriptionPropertiesKey="ALL_SOULS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="8"
			descriptionPropertiesKey="ST_DEMETRIUS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="ID_AL_FITR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="ID_UL_ADHA" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="MAWLID_AN_NABI" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="rs"
		description="Republika Srpska">
		<tns:Holiday>
			<tns:Fixed month="JANUARY" day="9"
				descriptionPropertiesKey="REPUBLIC_DAY" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="VICTORY" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:Fixed month="NOVEMBER" day="21"
				descriptionPropertiesKey="DAYTON" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="fbh"
		description="Federation of Bosnia and Herzegovina">
		<tns:Holiday>
			<tns:Fixed month="MARCH" day="1" descriptionPropertiesKey="INDEPENDENCE" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:Fixed month="NOVEMBER" day="25"
				descriptionPropertiesKey="NATIONAL_DAY" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_ng.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ng" description="Nigeria"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="27" descriptionPropertiesKey="CHILDRENS_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="29" descriptionPropertiesKey="FREEDOM_DEMOCRACY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="OCTOBER" day="1" descriptionPropertiesKey="INDEPENDENCE" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="26"
			descriptionPropertiesKey="BOXING_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER_MONDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="RAMADAN" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="MAWLID_AN_NABI" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="ID_AL_FITR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="ID_UL_ADHA" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="lag"
		description="Lagos">
		<tns:Holiday>
			<tns:Fixed month="JUNE" day="12" descriptionPropertiesKey="ELECTION" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_br.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="br" description="Brazil"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="APRIL" day="21" descriptionPropertiesKey="TIRADENTES" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="SEPTEMBER" day="7"
			descriptionPropertiesKey="INDEPENDENCE" />
	</tns:Holiday>
	<tns:Holiday validFrom="1980">
		<tns:Fixed month="OCTOBER" day="12"
			descriptionPropertiesKey="APARECIDA" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="2"
			descriptionPropertiesKey="ALL_SOULS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="15"
			descriptionPropertiesKey="NATIONAL_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="CARNIVAL" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="ASH_WEDNESDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="rj"
		description="Rio de Janeiro">
		<tns:Holiday validFrom="2007">
			<tns:Fixed month="APRIL" day="23" descriptionPropertiesKey="ST_GEORGE" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:Fixed month="NOVEMBER" day="20"
				descriptionPropertiesKey="BLACK_AWARENESS" />
		</tns:Holiday>
		<tns:SubConfigurations hierarchy="crj"
			description="City of Rio de Janeiro">
			<tns:Holiday>
				<tns:Fixed month="JANUARY" day="20"
					descriptionPropertiesKey="ST_SEBASTIAN" />
			</tns:Holiday>
			<tns:Holiday validTo="2006">
				<tns:Fixed month="APRIL" day="23"
					descriptionPropertiesKey="ST_GEORGE" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="s" description="Sao Paulo">
		<tns:Holiday>
			<tns:Fixed month="JULY" day="9" descriptionPropertiesKey="CONST_REVOLUTION" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:Fixed month="NOVEMBER" day="20"
				descriptionPropertiesKey="BLACK_AWARENESS" />
		</tns:Holiday>
		<tns:SubConfigurations hierarchy="cs"
			description="City of Sao Paulo">
			<tns:Holiday>
				<tns:Fixed month="JANUARY" day="25"
					descriptionPropertiesKey="FOUNDATION" />
			</tns:Holiday>
			<tns:Holiday>
				<tns:Fixed month="NOVEMBER" day="4"
					descriptionPropertiesKey="FOUNDATION" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="mg"
		description="Minas Gerais">
		<tns:SubConfigurations hierarchy="bh"
			description="Belo Horizonte">
			<tns:Holiday>
				<tns:Fixed month="AUGUST" day="15"
					descriptionPropertiesKey="LADY_GOOD_VOYAGE" />
			</tns:Holiday>
			<tns:Holiday>
				<tns:Fixed month="DECEMBER" day="8"
					descriptionPropertiesKey="LADY_CONCEICAO" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="ms"
		description="Mato Grosso do Sul">
		<tns:Holiday>
			<tns:Fixed month="OCTOBER" day="11"
				descriptionPropertiesKey="FOUNDATION" />
		</tns:Holiday>
		<tns:SubConfigurations hierarchy="cg"
			description="Campo Grande">
			<tns:Holiday>
				<tns:Fixed month="AUGUST" day="26"
					descriptionPropertiesKey="FOUNDATION" />
			</tns:Holiday>
		</tns:SubConfigurations>
		<tns:SubConfigurations hierarchy="do"
			description="Dourados">
			<tns:Holiday>
				<tns:Fixed month="DECEMBER" day="8"
					descriptionPropertiesKey="LADY_CONCEICAO" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="pr"
		description="Parana">
		<tns:SubConfigurations hierarchy="cu"
			description="Curitiba">
			<tns:Holiday>
				<tns:Fixed month="SEPTEMBER" day="8"
					descriptionPropertiesKey="LADY_LIGHT_PINE" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="rs"
		description="Rio Grande do Sul">
		<tns:Holiday>
			<tns:Fixed month="SEPTEMBER" day="20"
				descriptionPropertiesKey="FARROUS_REVOLUTION" />
		</tns:Holiday>
		<tns:SubConfigurations hierarchy="sm"
			description="Santa Maria">
			<tns:Holiday>
				<tns:Fixed month="DECEMBER" day="8"
					descriptionPropertiesKey="LADY_CONCEICAO" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="rn"
		description="Rio Grande do Norte">
		<tns:Holiday>
			<tns:Fixed month="OCTOBER" day="3"
				descriptionPropertiesKey="MARTYRS_DAY" />
		</tns:Holiday>
		<tns:SubConfigurations hierarchy="na"
			description="Natal">
			<tns:Holiday>
				<tns:Fixed month="NOVEMBER" day="21"
					descriptionPropertiesKey="LADY_APRESENTACAO" />
			</tns:Holiday>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="go"
		description="GoiÃ¡s">
		<tns:Holiday>
			<tns:Fixed month="OCTOBER" day="24"
				descriptionPropertiesKey="FOUNDATION" />
		</tns:Holiday>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="pe"
		description="Pernambuco">
		<tns:Holiday>
			<tns:Fixed month="DECEMBER" day="8"
				descriptionPropertiesKey="LADY_CONCEICAO" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_pa.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="pa" description="Panama"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" />
		<tns:Fixed month="JANUARY" day="9" />
		<tns:Fixed month="MAY" day="1" />
		<tns:Fixed month="NOVEMBER" day="3" />
		<tns:Fixed month="NOVEMBER" day="4" />
		<tns:Fixed month="NOVEMBER" day="5" />
		<tns:Fixed month="NOVEMBER" day="10" />
		<tns:Fixed month="NOVEMBER" day="28" />
		<tns:Fixed month="DECEMBER" day="8" />
		<tns:Fixed month="DECEMBER" day="25" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="CLEAN_MONDAY"/>
		<tns:ChristianHoliday type="CARNIVAL"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY"/>
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/holidays/Holidays_co.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="co" description="Colombia"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY">
			<tns:MovingCondition substitute="TUESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="WEDNESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY" />
		</tns:Fixed>
		<tns:Fixed month="MARCH" day="19" descriptionPropertiesKey="ST_JOSEPH">
			<tns:MovingCondition substitute="TUESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="WEDNESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY" />
		</tns:Fixed>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="JUNE" day="29" descriptionPropertiesKey="ST_PETER_PAUL">
			<tns:MovingCondition substitute="TUESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="WEDNESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY" />
		</tns:Fixed>
		<tns:Fixed month="JULY" day="20" descriptionPropertiesKey="INDEPENDENCE"/>
		<tns:Fixed month="AUGUST" day="7" descriptionPropertiesKey="BOYACA"/>
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_MARY">
			<tns:MovingCondition substitute="TUESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="WEDNESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY" />
		</tns:Fixed>
		<tns:Fixed month="OCTOBER" day="12" descriptionPropertiesKey="COLUMBUS_DAY">
			<tns:MovingCondition substitute="TUESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="WEDNESDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY" />
		</tns:Fixed>
		<tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
		<tns:Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="CARTAGENA"/>
		<tns:Fixed month="DECEMBER" day="8" descriptionPropertiesKey="IMMACULATE_CONCEPTION"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="MAUNDY_THURSDAY" />
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
		<tns:ChristianHoliday type="ASCENSION_DAY" />
		<tns:ChristianHoliday type="CORPUS_CHRISTI" />
		<tns:ChristianHoliday type="SACRED_HEART" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/test/resources/holidays/Holidays_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="test" description="Test holidays"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../../../main/resources/Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="16" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SATURDAY</tns:when>
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="23"/>
		<tns:MovingCondition to="PREVIOUS" weekday="WEDNESDAY"/>
	</tns:Holiday>
	<tns:Holiday>
		<tns:FixedWeekdayInMonth which="FOURTH" weekday="MONDAY"
				month="NOVEMBER" />
		<tns:MovingCondition to="NEXT" weekday="FRIDAY">
			<tns:when>MONDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:FixedWeekdayInMonth which="LAST" weekday="MONDAY"
			month="AUGUST" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER_MONDAY"
			chronology="GREGORIAN" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="ASH_WEDNESDAY" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="level1">
		<tns:Holiday>
			<tns:Fixed month="JANUARY" day="2" />
		</tns:Holiday>
		<tns:SubConfigurations hierarchy="level2">
			<tns:Holiday>
				<tns:Fixed month="JANUARY" day="3" />
			</tns:Holiday>
</tns:SubConfigurations>
</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="level11">
		<tns:Holiday>
			<tns:IslamicHoliday type="ID_AL_FITR" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="NEWYEAR" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="ASCHURA" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="LAILAT_AL_BARAT" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="LAILAT_AL_MIRAJ" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="LAILAT_AL_QADR" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="MAWLID_AN_NABI" />
		</tns:Holiday>
		<tns:Holiday>
			<tns:IslamicHoliday type="RAMADAN" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>
