=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://jollyday.sourceforge.net/Jollyday"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:jolly="http://jollyday.sourceforge.net/Jollyday">

	<simpleType name="Weekday">
		<restriction base="string">
			<enumeration value="MONDAY"></enumeration>
			<enumeration value="TUESDAY"></enumeration>
			<enumeration value="WEDNESDAY"></enumeration>
			<enumeration value="THURSDAY"></enumeration>
			<enumeration value="FRIDAY"></enumeration>
			<enumeration value="SATURDAY"></enumeration>
			<enumeration value="SUNDAY"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="Month">
		<restriction base="string">
			<enumeration value="JANUARY"></enumeration>
			<enumeration value="FEBRUARY"></enumeration>
			<enumeration value="MARCH"></enumeration>
			<enumeration value="MAY"></enumeration>
			<enumeration value="JUNE"></enumeration>
			<enumeration value="JULY"></enumeration>
			<enumeration value="AUGUST"></enumeration>
			<enumeration value="SEPTEMBER"></enumeration>
			<enumeration value="OCTOBER"></enumeration>
			<enumeration value="NOVEMBER"></enumeration>
			<enumeration value="DECEMBER"></enumeration>
			<enumeration value="APRIL"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="CycleType">
		<annotation>
			<appinfo>
				<typesafeEnumClass map="true" />
			</appinfo>
		</annotation>
		<restriction base="string">
			<enumeration value="EVERY_YEAR"></enumeration>
			<enumeration value="TWO_YEARS"></enumeration>
			<enumeration value="THREE_YEARS"></enumeration>
			<enumeration value="FOUR_YEARS"></enumeration>
			<enumeration value="FIVE_YEARS"></enumeration>
			<enumeration value="SIX_YEARS"></enumeration>
			<enumeration value="SEVEN_YEARS"></enumeration>
			<enumeration value="ODD_YEARS"></enumeration>
			<enumeration value="EVEN_YEARS"></enumeration>
		</restriction>
	</simpleType>

	<element name="Configuration" type="jolly:Configuration"></element>

	<complexType name="Configuration">
		<sequence>
			<element name="Holiday" type="jolly:HolidayRule" maxOccurs="unbounded"
				minOccurs="0"></element>
			<element name="SubConfigurations" type="jolly:Configuration"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="hierarchy" type="string"></attribute>
		<attribute name="description" type="string"></attribute>
	</complexType>

	<complexType name="Fixed">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="month" type="jolly:Month"></attribute>

				<attribute name="day">
					<simpleType>
						<restriction base="int">
							<minInclusive value="1"></minInclusive>
							<maxInclusive value="31"></maxInclusive>
						</restriction>
					</simpleType>
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="When">
		<restriction base="string">
			<enumeration value="BEFORE"></enumeration>
			<enumeration value="AFTER"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="FixedWeekdayInMonth">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="which" type="jolly:Which"></attribute>

				<attribute name="weekday" type="jolly:Weekday"></attribute>

				<attribute name="month" type="jolly:Month"></attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="Which">
		<restriction base="string">
			<enumeration value="FIRST"></enumeration>
			<enumeration value="SECOND"></enumeration>
			<enumeration value="THIRD"></enumeration>
			<enumeration value="LAST"></enumeration>
			<enumeration value="FOURTH"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="IslamicHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:IslamicHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="IslamicHolidayType">
		<restriction base="string">
			<enumeration value="NEWYEAR"></enumeration>
			<enumeration value="ASCHURA"></enumeration>
			<enumeration value="MAWLID_AN_NABI"></enumeration>
			<enumeration value="LAILAT_AL_MIRAJ"></enumeration>
			<enumeration value="LAILAT_AL_BARAT"></enumeration>
			<enumeration value="RAMADAN"></enumeration>
			<enumeration value="LAILAT_AL_QADR"></enumeration>
			<enumeration value="ID_AL_FITR"></enumeration>
			<enumeration value="ID_UL_ADHA"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="ChronologyType">
		<restriction base="string">
			<enumeration value="JULIAN"></enumeration>
			<enumeration value="GREGORIAN"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="ChristianHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:ChristianHolidayType">
				</attribute>

				<attribute name="chronology" type="jolly:ChronologyType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="HolidayType">
		<restriction base="string">
			<enumeration value="OFFICIAL_HOLIDAY" />
			<enumeration value="UNOFFICIAL_HOLIDAY" />
		</restriction>
	</simpleType>

	<simpleType name="ChristianHolidayType">
		<restriction base="string">
			<enumeration value="GOOD_FRIDAY"></enumeration>
			<enumeration value="EASTER_MONDAY"></enumeration>
			<enumeration value="ASCENSION_DAY"></enumeration>
			<enumeration value="WHIT_MONDAY"></enumeration>
			<enumeration value="CORPUS_CHRISTI"></enumeration>
			<enumeration value="MAUNDY_THURSDAY"></enumeration>
			<enumeration value="ASH_WEDNESDAY"></enumeration>
			<enumeration value="MARDI_GRAS"></enumeration>
			<enumeration value="GENERAL_PRAYER_DAY"></enumeration>
			<enumeration value="CLEAN_MONDAY"></enumeration>
			<enumeration value="SHROVE_MONDAY"></enumeration>
			<enumeration value="PENTECOST"></enumeration>
			<enumeration value="CARNIVAL"></enumeration>
			<enumeration value="EASTER_SATURDAY"></enumeration>
			<enumeration value="EASTER_TUESDAY"></enumeration>
			<enumeration value="SACRED_HEART"></enumeration>
			<enumeration value="EASTER"></enumeration>
			<enumeration value="PENTECOST_MONDAY"></enumeration>
			<enumeration value="WHIT_SUNDAY"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="Holiday" abstract="true">
		<attribute name="descriptionPropertiesKey" type="string" />
		<attribute name="localizedType" type="jolly:HolidayType"
			default="OFFICIAL_HOLIDAY" />
	</complexType>


	<simpleType name="To">
		<restriction base="string">
			<enumeration value="NEXT"></enumeration>
			<enumeration value="PREVIOUS"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="MovingCondition">
		<sequence>
			<element name="when" type="jolly:Weekday" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="to" type="jolly:To"></attribute>
		<attribute name="weekday" type="jolly:Weekday"></attribute>
	</complexType>

	<simpleType name="HinduHolidayType">
		<restriction base="string">
			<enumeration value="HOLI"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="HinduHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:HinduHolidayType"></attribute>
			</extension>
		</complexContent>
	</complexType>





	<simpleType name="HebrewHolidayType">
		<restriction base="string">
			<enumeration value="ROSH_HASHANAH"></enumeration>
			<enumeration value="ASERET_YEMEI_TESHUVA"></enumeration>
			<enumeration value="YOM_KIPPUR"></enumeration>
			<enumeration value="SUKKOT"></enumeration>
			<enumeration value="SHEMINI_ATZERET"></enumeration>
			<enumeration value="HANUKKAH"></enumeration>
			<enumeration value="ASARAH_BETEVET"></enumeration>
			<enumeration value="TU_BISHVAT"></enumeration>
			<enumeration value="PURIM"></enumeration>
			<enumeration value="1_NISAN"></enumeration>
			<enumeration value="PESACH"></enumeration>
			<enumeration value="SEFIRAH"></enumeration>
			<enumeration value="LAG_BAOMER"></enumeration>
			<enumeration value="SHAVOUT"></enumeration>
			<enumeration value="17_TAMMUZ"></enumeration>
			<enumeration value="TISHA_BAV"></enumeration>
			<enumeration value="1_ELUL"></enumeration>
			<enumeration value="ROSH_CODESH"></enumeration>
			<enumeration value="SHABBAT"></enumeration>
			<enumeration value="YOM_HASHOAH"></enumeration>
			<enumeration value="YOM_HAZIKARON"></enumeration>
			<enumeration value="YOM_HAATZAMAUT"></enumeration>
			<enumeration value="YOM_YERUSHALAIM"></enumeration>
		</restriction>
	</simpleType>


	<complexType name="EthiopianOrthodoxHoliday">
		<complexContent>
			<extension base="jolly:Holiday">
				<attribute name="type" type="jolly:EthiopianOrthodoxHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="EthiopianOrthodoxHolidayType">
		<restriction base="string">
			<enumeration value="TIMKAT"></enumeration>
			<enumeration value="ENKUTATASH"></enumeration>
			<enumeration value="MESKEL"></enumeration>
		</restriction>
	</simpleType>



	<complexType name="RelativeToEasterSunday">
		<complexContent>
			<extension base="jolly:Holiday">
				<sequence>
					<element name="chronology" type="jolly:ChronologyType">
					</element>
					<element name="days" type="int"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="HolidayRule">
		<sequence>
			<choice>
				<element name="Fixed" type="jolly:Fixed"></element>
				<element name="FixedWeekdayInMonth" type="jolly:FixedWeekdayInMonth">
				</element>
				<element name="RelativeToEasterSunday" type="jolly:RelativeToEasterSunday">
				</element>
				<element name="IslamicHoliday" type="jolly:IslamicHoliday"></element>
				<element name="HinduHoliday" type="jolly:HinduHoliday"></element>
				<element name="EthiopianOrthodoxHoliday" type="jolly:EthiopianOrthodoxHoliday">
				</element>
				<element name="ChristianHoliday" type="jolly:ChristianHoliday">
				</element>
			</choice>
			<sequence>
				<element name="MovingCondition" type="jolly:MovingCondition"
					minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</sequence>

		<attribute name="id" type="string"></attribute>
		<attribute name="validFrom" type="int"></attribute>
		<attribute name="validTo" type="int"></attribute>
		<attribute name="every" type="jolly:CycleType" default="EVERY_YEAR"></attribute>
	</complexType>

	<complexType name="HolidayRuleRef">
		<attribute name="ref" type="string"></attribute>
	</complexType>

</schema>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_mx.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="mx" description="Mexico"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="FEBRUARY" day="19" localizedType="UNOFFICIAL_HOLIDAY"
			descriptionPropertiesKey="ARMY_DAY" />
	</tns:Holiday>
	<tns:Holiday validFrom="1937">
		<tns:Fixed month="FEBRUARY" day="24" localizedType="UNOFFICIAL_HOLIDAY"
			descriptionPropertiesKey="FLAG_DAY" />
	</tns:Holiday>
	<tns:Holiday validFrom="1938">
		<tns:Fixed month="MARCH" day="18" localizedType="UNOFFICIAL_HOLIDAY"
			descriptionPropertiesKey="FLAG_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="OCTOBER" day="12" localizedType="UNOFFICIAL_HOLIDAY"
			descriptionPropertiesKey="COLUMBUS_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
		<tns:MovingCondition to="PREVIOUS" weekday="FRIDAY">
			<tns:when>SATURDAY</tns:when>
		</tns:MovingCondition>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
		<tns:MovingCondition to="PREVIOUS" weekday="FRIDAY">
			<tns:when>SATURDAY</tns:when>
		</tns:MovingCondition>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="SEPTEMBER" day="16"
			descriptionPropertiesKey="INDEPENDENCE" />
		<tns:MovingCondition to="PREVIOUS" weekday="FRIDAY">
			<tns:when>SATURDAY</tns:when>
		</tns:MovingCondition>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1934" every="6_YEARS">
		<tns:Fixed month="DECEMBER" day="1"
			descriptionPropertiesKey="GOVERNMENT_CHANGE" />
		<tns:MovingCondition to="PREVIOUS" weekday="FRIDAY">
			<tns:when>SATURDAY</tns:when>
		</tns:MovingCondition>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
		<tns:MovingCondition to="PREVIOUS" weekday="FRIDAY">
			<tns:when>SATURDAY</tns:when>
		</tns:MovingCondition>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:FixedWeekdayInMonth which="FIRST"
			weekday="MONDAY" month="FEBRUARY" descriptionPropertiesKey="CONSTITUTION_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:FixedWeekdayInMonth which="THIRD"
			weekday="MONDAY" month="MARCH" descriptionPropertiesKey="JUAREZ_BIRTHDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:FixedWeekdayInMonth which="THIRD"
			weekday="MONDAY" month="NOVEMBER" descriptionPropertiesKey="REVOLUTION" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="pue"
		description="Puebla">
		<tns:Holiday>
			<tns:Fixed month="MAY" day="5" descriptionPropertiesKey="MAY_DAY"
				localizedType="UNOFFICIAL_HOLIDAY" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_za.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="za" description="South Africa"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="2000" validTo="2000">
		<tns:Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MARCH" day="21" descriptionPropertiesKey="HUMAN_RIGHTS" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1952" validTo="1974">
		<tns:Fixed month="APRIL" day="6" descriptionPropertiesKey="RIEBEECK" />
	</tns:Holiday>
	<tns:Holiday validFrom="1980" validTo="1994">
		<tns:Fixed month="APRIL" day="6" descriptionPropertiesKey="FOUNDATION" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="APRIL" day="27" descriptionPropertiesKey="FREEDOM" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1990">
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="2008" validTo="2008">
		<tns:Fixed month="MAY" day="2" descriptionPropertiesKey="HUMAN_RIGHTS" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1910" validTo="1951">
		<tns:Fixed month="MAY" day="24" descriptionPropertiesKey="EMPIRE" />
	</tns:Holiday>
	<tns:Holiday validFrom="1910" validTo="1993">
		<tns:Fixed month="MAY" day="31" descriptionPropertiesKey="REPUBLIC_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="YOUTH" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1961" validTo="1974">
		<tns:Fixed month="JULY" day="10" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="9" descriptionPropertiesKey="INTERNATIONAL_WOMAN" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="SEPTEMBER" day="24"
			descriptionPropertiesKey="HERITAGE" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1952" validTo="1993">
		<tns:Fixed month="OCTOBER" day="10"
			descriptionPropertiesKey="KRUGER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="16"
			descriptionPropertiesKey="RECONCILIATION" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="26"
			descriptionPropertiesKey="GOODWILL" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1999" validTo="1999">
		<tns:Fixed month="DECEMBER" day="31"
			descriptionPropertiesKey="NEW_YEAR" />
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="1987" validTo="1989">
		<tns:FixedWeekdayInMonth which="FIRST"
			weekday="FRIDAY" month="MAY" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday validFrom="1952" validTo="1960">
		<tns:FixedWeekdayInMonth which="SECOND"
			weekday="MONDAY" month="JULY" descriptionPropertiesKey="QUEENS_BIRTHDAY" />
	</tns:Holiday>
	<tns:Holiday validTo="1951">
		<tns:FixedWeekdayInMonth which="FIRST"
			weekday="MONDAY" month="AUGUST" descriptionPropertiesKey="KINGS_DAY" />
	</tns:Holiday>
	<tns:Holiday validFrom="1952" validTo="1979">
		<tns:FixedWeekdayInMonth which="FIRST"
			weekday="MONDAY" month="SEPTEMBER" descriptionPropertiesKey="SETTLER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER_MONDAY" />
	</tns:Holiday>
	<tns:Holiday validFrom="1910" validTo="1993">
		<tns:ChristianHoliday type="ASCENSION_DAY" />
	</tns:Holiday>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_ua.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ua" description="Ukraine"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MARCH" day="8" descriptionPropertiesKey="INTERNATIONAL_WOMAN" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="2" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="VICTORY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JUNE" day="28" descriptionPropertiesKey="CONSTITUTION_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="24" descriptionPropertiesKey="INDEPENDENCE" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER" chronology="JULIAN" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER_MONDAY"
			chronology="JULIAN" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="PENTECOST"
			chronology="JULIAN" />
	</tns:Holiday>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_al.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="al" description="Albania"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SATURDAY</tns:when>
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SATURDAY</tns:when>
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="2004">
		<tns:Fixed month="MARCH" day="14" descriptionPropertiesKey="SPRING_DAY"/>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SATURDAY</tns:when>
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SATURDAY</tns:when>
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday validFrom="2003">
		<tns:Fixed month="OCTOBER" day="19" descriptionPropertiesKey="MOTHER_TERESA"/>
		<tns:MovingCondition to="NEXT" weekday="MONDAY">
			<tns:when>SATURDAY</tns:when>
			<tns:when>SUNDAY</tns:when>
		</tns:MovingCondition>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="28" descriptionPropertiesKey="INDEPENDENCE"/>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="29" descriptionPropertiesKey="LIBERATION"/>
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER_MONDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="ID_UL_ADHA" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:IslamicHoliday type="ID_AL_FITR" />
	</tns:Holiday>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday-test/src/test/resources/holidays/Holidays_test_is_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="is" description="Iceland"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="APRIL" day="4"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
		<tns:Fixed month="DECEMBER" day="26"/>
		<tns:Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
		<tns:Fixed month="JANUARY" day="1"/>
		<tns:Fixed month="JANUARY" day="6"/>
		<tns:Fixed month="MAY" day="13"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="APRIL" day="5"/>
		<tns:Fixed month="DECEMBER" day="1"/>
		<tns:Fixed month="JUNE" day="17"/>
		<tns:Fixed month="JUNE" day="24"/>
		<tns:Fixed month="DECEMBER" day="31"/>
		<tns:Fixed month="FEBRUARY" day="18"/>
		<tns:Fixed month="MARCH" day="1"/>
		<tns:Fixed month="NOVEMBER" day="16"/>
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/branches/v_0_5_0/src/main/resources/holidays/Holidays_it.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="it" description="Italy"
	xmlns:tns="http://jollyday.sourceforge.net/Jollyday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jollyday.sourceforge.net/Jollyday ../Holiday.xsd">
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="APRIL" day="25" descriptionPropertiesKey="LIBERATION" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="JUNE" day="2" descriptionPropertiesKey="REPUBLIC_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="NOVEMBER" day="1"
			descriptionPropertiesKey="ALL_SAINTS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="8"
			descriptionPropertiesKey="IMMACULATE_CONCEPTION" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:Fixed month="DECEMBER" day="26"
			descriptionPropertiesKey="STEPHENS" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER" />
	</tns:Holiday>
	<tns:Holiday>
		<tns:ChristianHoliday type="EASTER_MONDAY" />
	</tns:Holiday>
	<tns:SubConfigurations hierarchy="bz"
		description="SÃ¼dtirol">
		<tns:Holiday>
			<tns:ChristianHoliday type="WHIT_MONDAY" />
		</tns:Holiday>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/tags/v_0_4_5/trunk/src/main/resources/holidays/Holidays_be.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="be" description="Belgium"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" localizedType="OFFICIAL_HOLIDAY" />
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY" localizedType="OFFICIAL_HOLIDAY" />
		<tns:Fixed month="JULY" day="21" descriptionPropertiesKey="NATIONAL_DAY" localizedType="OFFICIAL_HOLIDAY" />
		<tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY" />
		<tns:Fixed month="NOVEMBER" day="1" localizedType="OFFICIAL_HOLIDAY"
			descriptionPropertiesKey="ALL_SAINTS" />
		<tns:Fixed month="NOVEMBER" day="2" localizedType="UNOFFICIAL_HOLIDAY"
			descriptionPropertiesKey="ALL_SOULS" />
		<tns:Fixed month="NOVEMBER" day="11" localizedType="OFFICIAL_HOLIDAY"
			descriptionPropertiesKey="ARMISTICE" />
		<tns:Fixed month="DECEMBER" day="25" localizedType="OFFICIAL_HOLIDAY"
			descriptionPropertiesKey="CHRISTMAS" />
		<tns:Fixed month="NOVEMBER" day="15" localizedType="UNOFFICIAL_HOLIDAY"
			descriptionPropertiesKey="KINGS_FEAST" />
		<tns:Fixed month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE" localizedType="UNOFFICIAL_HOLIDAY" />
		<tns:ChristianHoliday type="EASTER" localizedType="OFFICIAL_HOLIDAY" />
		<tns:ChristianHoliday type="EASTER_MONDAY" localizedType="OFFICIAL_HOLIDAY" />
		<tns:ChristianHoliday type="ASCENSION_DAY" localizedType="OFFICIAL_HOLIDAY" />
		<tns:ChristianHoliday type="WHIT_MONDAY" localizedType="OFFICIAL_HOLIDAY" />
		<tns:ChristianHoliday type="PENTECOST" localizedType="OFFICIAL_HOLIDAY" />
		<tns:ChristianHoliday type="PENTECOST_MONDAY" localizedType="OFFICIAL_HOLIDAY" />
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/tags/v_0_4_5/tags/v_0_2_0/jollyday/src/main/resources/Holidays_hr.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="hr" description="Croatia" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="JANUARY" day="6"/>
	  <tns:Fixed month="MAY" day="1"/>
	  <tns:Fixed month="JUNE" day="22"/>
	  <tns:Fixed month="JUNE" day="25"/>
	  <tns:Fixed month="AUGUST" day="5"/>
	  <tns:Fixed month="AUGUST" day="15"/>
	  <tns:Fixed month="OCTOBER" day="8"/>
	  <tns:Fixed month="NOVEMBER" day="1"/>
	  <tns:Fixed month="DECEMBER" day="25"/>
	  <tns:Fixed month="DECEMBER" day="26"/>
	  <tns:ChristianHoliday type="EASTER_MONDAY"/>
	  <tns:ChristianHoliday type="CORPUS_CHRISTI"/>
  </tns:Holidays>
</tns:Configuration>
