=== svendiedrichsen/jollyday/src/main/xsd/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Holiday"
	xmlns:tns="http://www.example.org/Holiday" elementFormDefault="qualified">

	<simpleType name="Weekday">
		<restriction base="string">
			<enumeration value="MONDAY"/>
			<enumeration value="TUESDAY"/>
			<enumeration value="WEDNESDAY"/>
			<enumeration value="THURSDAY"/>
			<enumeration value="FRIDAY"/>
			<enumeration value="SATURDAY"/>
			<enumeration value="SUNDAY"/>
		</restriction>
	</simpleType>

	<simpleType name="Month">
		<restriction base="string">
			<enumeration value="JANUARY"/>
			<enumeration value="FEBRUARY"/>
			<enumeration value="MARCH"/>
			<enumeration value="APRIL"/>
			<enumeration value="MAY"/>
			<enumeration value="JUNE"/>
			<enumeration value="JULY"/>
			<enumeration value="AUGUST"/>
			<enumeration value="SEPTEMBER"/>
			<enumeration value="OCTOBER"/>
			<enumeration value="NOVEMBER"/>
			<enumeration value="DECEMBER"/>
		</restriction>
	</simpleType>


	<complexType name="RelativeToFixed">
		<complexContent>
			<extension base="tns:Holiday">
				<sequence>
					<choice maxOccurs="1" minOccurs="1">
						<element name="Days" type="int" maxOccurs="1" minOccurs="0">
						</element>
						<element name="Weekday" type="tns:Weekday" maxOccurs="1"
							minOccurs="0">
						</element>
					</choice>
					<element name="When" type="tns:When"/>
					<element name="Date" type="tns:Fixed"/>
				</sequence>

			</extension>
		</complexContent>
	</complexType>




	<complexType name="Holidays">
		<sequence>
			<element name="Fixed" type="tns:Fixed" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="RelativeToFixed" type="tns:RelativeToFixed"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="RelativeToWeekdayInMonth"
				type="tns:RelativeToWeekdayInMonth" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="FixedWeekday" type="tns:FixedWeekdayInMonth"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="ChristianHoliday" type="tns:ChristianHoliday"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="ChineseHoliday" type="tns:ChineseHoliday"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="IslamicHoliday" type="tns:IslamicHoliday"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="FixedWeekdayBetweenFixed"
				type="tns:FixedWeekdayBetweenFixed" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="FixedWeekdayRelativeToFixed"
				type="tns:FixedWeekdayRelativeToFixed" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="HinduHoliday" type="tns:HinduHoliday"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="HebrewHoliday" type="tns:HebrewHoliday"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="EthiopianOrthodoxHoliday"
				type="tns:EthiopianOrthodoxHoliday" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="RelativeToEasterSunday" type="tns:RelativeToEasterSunday" minOccurs="0"
					 maxOccurs="unbounded"/>
		</sequence>




	</complexType>


	<element name="Configuration" type="tns:Configuration"/>

	<complexType name="Configuration">
		<sequence>
			<element name="Holidays" type="tns:Holidays"/>
			<element name="SubConfigurations" type="tns:Configuration"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="hierarchy" type="string"/>
		<attribute name="description" type="string"/>
	</complexType>

	<complexType name="Fixed">
		<complexContent>
			<extension base="tns:MoveableHoliday">
				<attribute name="month" type="tns:Month"/>

				<attribute name="day">
					<simpleType>
						<restriction base="int">
							<minInclusive value="1"/>
							<maxInclusive value="31"/>
						</restriction>
					</simpleType>
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="When">
		<restriction base="string">
			<enumeration value="BEFORE"/>
			<enumeration value="AFTER"/>
		</restriction>
	</simpleType>


	<complexType name="FixedWeekdayInMonth">
		<complexContent>
			<extension base="tns:Holiday">
				<attribute name="which" type="tns:Which"/>

				<attribute name="weekday" type="tns:Weekday"/>

				<attribute name="month" type="tns:Month"/>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="Which">
		<restriction base="string">
			<enumeration value="FIRST"/>
			<enumeration value="SECOND"/>
			<enumeration value="THIRD"/>
			<enumeration value="FOURTH"/>
			<enumeration value="LAST"/>
		</restriction>
	</simpleType>

	<complexType name="RelativeToWeekdayInMonth">
		<complexContent>
			<extension base="tns:Holiday">
				<sequence>
					<element name="FixedWeekday" type="tns:FixedWeekdayInMonth"/>
				</sequence>
				<attribute name="weekday" type="tns:Weekday"/>
				<attribute name="when" type="tns:When"/>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="IslamicHoliday">
		<complexContent>
			<extension base="tns:Holiday">
				<attribute name="type" type="tns:IslamicHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>


	<simpleType name="IslamicHolidayType">
		<restriction base="string">
			<enumeration value="NEWYEAR"/>
			<enumeration value="ASCHURA"/>
			<enumeration value="MAWLID_AN_NABI"/>
			<enumeration value="LAILAT_AL_MIRAJ"/>
			<enumeration value="LAILAT_AL_BARAT"/>
			<enumeration value="RAMADAN"/>
			<enumeration value="LAILAT_AL_QADR"/>
			<enumeration value="ID_AL_FITR"/>
			<enumeration value="ID_UL_ADHA"/>
		</restriction>
	</simpleType>

	<simpleType name="ChronologyType">
		<restriction base="string">
			<enumeration value="JULIAN"/>
			<enumeration value="GREGORIAN"/>
		</restriction>
	</simpleType>

	<complexType name="ChristianHoliday">
		<complexContent>
			<extension base="tns:MoveableHoliday">
				<attribute name="type" type="tns:ChristianHolidayType">
				</attribute>

				<attribute name="chronology" type="tns:ChronologyType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="HolidayType">
		<restriction base="string">
			<enumeration value="OFFICIAL_HOLIDAY" />
			<enumeration value="UNOFFICIAL_HOLIDAY" />
		</restriction>
	</simpleType>

	<simpleType name="ChristianHolidayType">
		<restriction base="string">
			<enumeration value="GOOD_FRIDAY"/>
			<enumeration value="EASTER_MONDAY"/>
			<enumeration value="ASCENSION_DAY"/>
			<enumeration value="WHIT_MONDAY"/>
			<enumeration value="CORPUS_CHRISTI"/>
			<enumeration value="MAUNDY_THURSDAY"/>
			<enumeration value="ASH_WEDNESDAY"/>
			<enumeration value="MARDI_GRAS"/>
			<enumeration value="GENERAL_PRAYER_DAY"/>
			<enumeration value="CLEAN_MONDAY"/>
			<enumeration value="SHROVE_MONDAY"/>
			<enumeration value="PENTECOST"/>
			<enumeration value="CARNIVAL"/>
			<enumeration value="EASTER_SATURDAY"/>
			<enumeration value="EASTER_TUESDAY"/>
			<enumeration value="SACRED_HEART"/>
			<enumeration value="EASTER"/>
			<enumeration value="PENTECOST_MONDAY"/>
			<enumeration value="WHIT_SUNDAY"/>
		</restriction>
	</simpleType>

	<complexType name="FixedWeekdayBetweenFixed">
		<complexContent>
			<extension base="tns:Holiday">
				<sequence>
					<element name="from" type="tns:Fixed"/>
					<element name="to" type="tns:Fixed"/>
				</sequence>
				<attribute name="weekday" type="tns:Weekday"/>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Holiday" abstract="true">
		<attribute name="validFrom" type="int" use="optional" />
		<attribute name="validTo" type="int" />
		<attribute name="every" type="tns:HolidayCycleType" default="EVERY_YEAR" />
		<attribute name="descriptionPropertiesKey" type="string" />
		<attribute name="localizedType" type="tns:HolidayType"
			default="OFFICIAL_HOLIDAY" />
	</complexType>


	<simpleType name="Substituted">
		<restriction base="string">
			<enumeration value="ON_SATURDAY"/>
			<enumeration value="ON_SUNDAY"/>
			<enumeration value="ON_WEEKEND"/>
			<enumeration value="ON_TUESDAY"/>
			<enumeration value="ON_WEDNESDAY"/>
		</restriction>
	</simpleType>

	<simpleType name="With">
		<restriction base="string">
			<enumeration value="NEXT"/>
			<enumeration value="PREVIOUS"/>
		</restriction>
	</simpleType>



	<complexType name="MovingCondition">
		<attribute name="substitute" type="tns:Weekday"/>
		<attribute name="with" type="tns:With"/>
		<attribute name="weekday" type="tns:Weekday"/>
	</complexType>

	<simpleType name="HinduHolidayType">
		<restriction base="string">
			<enumeration value="HOLI"/>
		</restriction>
	</simpleType>

	<complexType name="HinduHoliday">
		<complexContent>
			<extension base="tns:Holiday">
				<attribute name="type" type="tns:HinduHolidayType"/>

			</extension>
		</complexContent>
	</complexType>



	<complexType name="MoveableHoliday" abstract="true">
		<complexContent>
			<extension base="tns:Holiday">
				<sequence>
					<element name="MovingCondition" type="tns:MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="HebrewHoliday">
		<complexContent>
			<extension base="tns:Holiday">
				<attribute name="type" type="tns:HebrewHolidayType"/>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="HebrewHolidayType">
		<restriction base="string">
			<enumeration value="ROSH_HASHANAH"/>
			<enumeration value="ASERET_YEMEI_TESHUVA"/>
			<enumeration value="YOM_KIPPUR"/>
			<enumeration value="SUKKOT"/>
			<enumeration value="SHEMINI_ATZERET"/>
			<enumeration value="HANUKKAH"/>
			<enumeration value="ASARAH_BETEVET"/>
			<enumeration value="TU_BISHVAT"/>
			<enumeration value="PURIM"/>
			<enumeration value="1_NISAN"/>
			<enumeration value="PESACH"/>
			<enumeration value="SEFIRAH"/>
			<enumeration value="LAG_BAOMER"/>
			<enumeration value="SHAVOUT"/>
			<enumeration value="17_TAMMUZ"/>
			<enumeration value="TISHA_BAV"/>
			<enumeration value="1_ELUL"/>
			<enumeration value="ROSH_CODESH"/>
			<enumeration value="SHABBAT"/>
			<enumeration value="YOM_HASHOAH"/>
			<enumeration value="YOM_HAZIKARON"/>
			<enumeration value="YOM_HAATZAMAUT"/>
			<enumeration value="YOM_YERUSHALAIM"/>
		</restriction>
	</simpleType>

	<complexType name="ChineseHoliday">
		<complexContent>
			<extension base="tns:Holiday">
				<attribute name="type" type="tns:ChineseHolidayType">
				</attribute>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="ChineseHolidayType">
		<restriction base="string">
			<enumeration value="NEW_YEAR"/>
			<enumeration value="QING_MING"/>
			<enumeration value="DRAGON_BOAT"/>
			<enumeration value="MID_AUTUMN"/>
			<enumeration value="CHUNG_YEUNG"/>
		</restriction>
	</simpleType>

	<complexType name="EthiopianOrthodoxHoliday">
		<complexContent>
			<extension base="tns:Holiday">
				<attribute name="type"
					type="tns:EthiopianOrthodoxHolidayType">
				</attribute>

			</extension>
		</complexContent>
	</complexType>

	<simpleType name="EthiopianOrthodoxHolidayType">
    	<restriction base="string">
			<enumeration value="TIMKAT"/>
			<enumeration value="ENKUTATASH"/>
			<enumeration value="MESKEL"/>
    	</restriction>
    </simpleType>

	<complexType name="FixedWeekdayRelativeToFixed">
		<complexContent>
			<extension base="tns:Holiday">
				<sequence>
					<element name="day" type="tns:Fixed"/>
				</sequence>
				<attribute name="which" type="tns:Which"/>
				<attribute name="weekday" type="tns:Weekday"/>
				<attribute name="when" type="tns:When"/>
			</extension>
		</complexContent>
	</complexType>


	<simpleType name="HolidayCycleType">
		<restriction base="string">
			<enumeration value="EVERY_YEAR"/>
			<enumeration value="2_YEARS"/>
			<enumeration value="4_YEARS"/>
			<enumeration value="5_YEARS"/>
			<enumeration value="6_YEARS"/>
			<enumeration value="ODD_YEARS"/>
			<enumeration value="EVEN_YEARS"/>
		</restriction>
	</simpleType>

	<complexType name="RelativeToEasterSunday">
		<complexContent>
			<extension base="tns:Holiday">
				<sequence>
					<element name="chronology"
						type="tns:ChronologyType">
					</element>
					<element name="days" type="int"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
</schema>

=== svendiedrichsen/jollyday/src/test/resources/holidays/Holidays_test_al_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="al" description="Albania" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1"/>
	  <tns:Fixed month="JANUARY" day="4"/>
	  <tns:Fixed month="MARCH" day="15"/>
	  <tns:Fixed month="MAY" day="3"/>
	  <tns:Fixed month="OCTOBER" day="19"/>
	  <tns:Fixed month="NOVEMBER" day="28"/>
	  <tns:Fixed month="NOVEMBER" day="29"/>
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:Fixed month="APRIL" day="5"/>
	  <tns:Fixed month="NOVEMBER" day="16"/>
	  <tns:Fixed month="SEPTEMBER" day="10"/>
  </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/src/test/resources/holidays/Holidays_test_gb_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="gb" description="United Kingdom"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="MAY" day="3" />
		<tns:Fixed month="MAY" day="31" />
		<tns:Fixed month="DECEMBER" day="27" />
		<tns:Fixed month="DECEMBER" day="28" />
		<tns:Fixed month="APRIL" day="2" />
	</tns:Holidays>
  <tns:SubConfigurations hierarchy="al" description="Alderney">
	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="1"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="en" description="England">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1"/>
		<tns:Fixed month="AUGUST" day="30"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="gu" description="Guernsey">
	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="1"/>
  		<tns:Fixed month="MAY" day="9"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="im" description="Isle of Man">
	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="1"/>
  		<tns:Fixed month="JUNE" day="11"/>
  		<tns:Fixed month="JULY" day="5"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="je" description="Jersey">
	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="1"/>
  		<tns:Fixed month="MAY" day="9"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="ni" description="Northern Ireland">
	<tns:Holidays>
  		<tns:Fixed month="JANUARY" day="1"/>
		<tns:Fixed month="MARCH" day="17"/>
		<tns:Fixed month="JULY" day="12"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sc" description="Scotland">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1"/>
		<tns:Fixed month="JANUARY" day="4"/>
		<tns:Fixed month="AUGUST" day="2"/>
  	</tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="wa" description="Wales">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1"/>
		<tns:Fixed month="AUGUST" day="2"/>
		<tns:Fixed month="APRIL" day="5" />
  	</tns:Holidays>
  </tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/main/resources/Holidays_fi.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="fi" description="Finland"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="holiday.description.NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="holiday.description.EPIPHANY"/>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="holiday.description.LABOUR_DAY"/>
		<tns:Fixed month="DECEMBER" day="6" descriptionPropertiesKey="holiday.description.INDEPENDENCE"/>
		<tns:Fixed month="DECEMBER" day="24" descriptionPropertiesKey="holiday.description.CHRISTMAS_EVE"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="holiday.description.CHRISTMAS"/>
		<tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="holiday.description.STEPHENS"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
		<tns:ChristianHoliday type="EASTER_MONDAY" />
		<tns:ChristianHoliday type="ASCENSION_DAY" />
		<tns:FixedWeekdayBetweenFixed weekday="FRIDAY" descriptionPropertiesKey="holiday.description.MIDSUMMER_EVE">
			<tns:from month="JUNE" day="19" />
			<tns:to month="JUNE" day="25" />
		</tns:FixedWeekdayBetweenFixed>
		<tns:FixedWeekdayBetweenFixed weekday="SATURDAY" descriptionPropertiesKey="holiday.description.MIDSUMMER">
			<tns:from month="JUNE" day="20" />
			<tns:to month="JUNE" day="26" />
		</tns:FixedWeekdayBetweenFixed>
		<tns:FixedWeekdayBetweenFixed weekday="SATURDAY" descriptionPropertiesKey="holiday.description.ALL_SAINTS">
			<tns:from month="OCTOBER" day="31" />
			<tns:to month="NOVEMBER" day="6" />
		</tns:FixedWeekdayBetweenFixed>
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/src/test/resources/holidays/Holidays_test_uy_2016.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="uy" description="Uruguay"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
		<tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
		<tns:Fixed month="APRIL" day="19" descriptionPropertiesKey="LANDING_33_EASTERNERS">
			<tns:MovingCondition substitute="TUESDAY" with="PREVIOUS" weekday="MONDAY"/>
			<tns:MovingCondition substitute="WEDNESDAY" with="PREVIOUS" weekday="MONDAY"/>
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY"/>
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY"/>
		</tns:Fixed>
		<tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>		
		<tns:Fixed month="MAY" day="18" descriptionPropertiesKey="LAS_PIEDRAS">
			<tns:MovingCondition substitute="TUESDAY" with="PREVIOUS" weekday="MONDAY"/>
			<tns:MovingCondition substitute="WEDNESDAY" with="PREVIOUS" weekday="MONDAY"/>
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY"/>
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY"/>
		</tns:Fixed>
		<tns:Fixed month="JUNE" day="19" descriptionPropertiesKey="ARTIGAS"/>
		<tns:Fixed month="JULY" day="18" descriptionPropertiesKey="CONSTITUTION_DAY"/>
		<tns:Fixed month="AUGUST" day="25" descriptionPropertiesKey="INDEPENDENCE"/>
		<tns:Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS"/>
		<tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
		<tns:Fixed month="OCTOBER" day="12" descriptionPropertiesKey="RACE">
			<tns:MovingCondition substitute="TUESDAY" with="PREVIOUS" weekday="MONDAY"/>
			<tns:MovingCondition substitute="WEDNESDAY" with="PREVIOUS" weekday="MONDAY"/>
			<tns:MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY"/>
			<tns:MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY"/>
		</tns:Fixed>
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="SHROVE_MONDAY" />
		<tns:ChristianHoliday type="CARNIVAL"/>
		<tns:ChristianHoliday type="MAUNDY_THURSDAY"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY"/>
	</tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/jollyday/src/test/resources/Holidays_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="test" description="Test holidays" xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Holiday Holiday.xsd ">
	<tns:Holidays>
		<tns:Fixed month="JANUARY" day="1"/>
		<tns:RelativeToFixed >
			<tns:Weekday>WEDNESDAY</tns:Weekday>
			<tns:When>BEFORE</tns:When>
			<tns:Date month="NOVEMBER" day="23"/>
		</tns:RelativeToFixed>
		<tns:RelativeToFixed >
			<tns:Days>5</tns:Days>
  			<tns:When>AFTER</tns:When>
  			<tns:Date month="NOVEMBER" day="23"/>
  		</tns:RelativeToFixed>
		<tns:RelativeToWeekdayInMonth weekday="FRIDAY" when="AFTER">
			<tns:FixedWeekday which="FOURTH" weekday="MONDAY" month="NOVEMBER"/>
		</tns:RelativeToWeekdayInMonth>
   		<tns:FixedMovingOnWeekend month="JANUARY" day="16" nextWeekday="MONDAY"/>		
  		<tns:FixedWeekday which="LAST" weekday="MONDAY" month="AUGUST"/>
		<tns:ChristianHoliday type="GOOD_FRIDAY"/>
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="level1">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="2"/>
		</tns:Holidays>
		<tns:SubConfigurations hierarchy="level2">
			<tns:Holidays>
				<tns:Fixed month="JANUARY" day="3"/>
			</tns:Holidays>
		</tns:SubConfigurations>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="level11">
		<tns:Holidays>
			<tns:IslamicHoliday type="ID_AL_FITR"/>
			<tns:IslamicHoliday type="ID_UL_ADHA"/>
			<tns:IslamicHoliday type="NEUJAHR" />
			<tns:IslamicHoliday type="ASCHURA" />
			<tns:IslamicHoliday type="LAILAT_AL_BARAT" />
			<tns:IslamicHoliday type="LAILAT_AL_MIRAJ" />
			<tns:IslamicHoliday type="LAILAT_AL_QADR" />
			<tns:IslamicHoliday type="MAWLID_AN_NABI" />
			<tns:IslamicHoliday type="RAMADAN" />
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>

=== svendiedrichsen/jollyday/src/test/resources/holidays/Holidays_test_se_2016.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="se" description="Sweden" xmlns:tns="http://www.example.org/Holiday"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
    <tns:Holidays>
        <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEARS_DAY"/>
        <tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
        <tns:Fixed month="MARCH" day="25" descriptionPropertiesKey="GOOD_FRIDAY"/>
        <tns:Fixed month="MARCH" day="27" descriptionPropertiesKey="EASTER"/>
        <tns:Fixed month="MARCH" day="28" descriptionPropertiesKey="EASTER_MONDAY"/>
        <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
        <tns:Fixed month="MAY" day="5" descriptionPropertiesKey="ASCENSION"/>
        <tns:Fixed month="MAY" day="15" descriptionPropertiesKey="PENTECOST"/>
        <tns:Fixed month="JUNE" day="6" descriptionPropertiesKey="NATIONAL_DAY"/>
        <tns:Fixed month="JUNE" day="24" descriptionPropertiesKey="MIDSUMMERS_EVE"/>
        <tns:Fixed month="JUNE" day="25" descriptionPropertiesKey="MIDSUMMERS_DAY"/>
        <tns:Fixed month="NOVEMBER" day="5" descriptionPropertiesKey="ALL_SAINTS_DAY"/>
        <tns:Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
        <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
        <tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
        <tns:Fixed month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE"/>
    </tns:Holidays>
</tns:Configuration>

=== svendiedrichsen/jollyday/src/main/resources/holidays/Holidays_gb.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="gb" description="United Kingdom"
	xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
	<tns:Holidays>
		<tns:Fixed month="DECEMBER" day="26"
			descriptionPropertiesKey="BOXING_DAY">
			<tns:MovingCondition substitute="SATURDAY" with="NEXT"
				weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT"
				weekday="TUESDAY" />
			<tns:MovingCondition substitute="MONDAY" with="NEXT"
				weekday="TUESDAY" />
		</tns:Fixed>
		<tns:Fixed month="DECEMBER" day="25"
			descriptionPropertiesKey="CHRISTMAS">
			<tns:MovingCondition substitute="SATURDAY" with="NEXT"
				weekday="MONDAY" />
			<tns:MovingCondition substitute="SUNDAY" with="NEXT"
				weekday="MONDAY" />
		</tns:Fixed>

		<!-- The 2020 bank holiday was moved from the 4th to the 8th of May -->
		<tns:Fixed month="MAY" day="8"
				   validFrom="2020" validTo="2020"
				   descriptionPropertiesKey="BANK_HOLIDAY" />
		
		<!-- King's Coronation gained an extra bank holiday -->
		<tns:Fixed month="MAY" day="8"
			   	validFrom="2023" validTo="2023"
			   	descriptionPropertiesKey="BANK_HOLIDAY" />

		<tns:FixedWeekday which="FIRST" weekday="MONDAY" validFrom="1900" validTo="2019"
						  month="MAY" descriptionPropertiesKey="BANK_HOLIDAY" />
		<tns:FixedWeekday which="FIRST" weekday="MONDAY" validFrom="2021"
						  month="MAY" descriptionPropertiesKey="BANK_HOLIDAY" />
		<tns:FixedWeekday which="LAST" weekday="MONDAY"
			month="MAY" descriptionPropertiesKey="BANK_HOLIDAY" />
		<tns:ChristianHoliday type="EASTER" />
		<tns:ChristianHoliday type="GOOD_FRIDAY" />
	</tns:Holidays>
	<tns:SubConfigurations hierarchy="al"
		description="Alderney">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR" />
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="en"
		description="England">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR">
				<tns:MovingCondition substitute="SATURDAY" with="NEXT"
					weekday="MONDAY" />
				<tns:MovingCondition substitute="SUNDAY" with="NEXT"
					weekday="MONDAY" />
			</tns:Fixed>
			<tns:FixedWeekday which="LAST" weekday="MONDAY"
				month="AUGUST" descriptionPropertiesKey="BANK_HOLIDAY" />
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="gu"
		description="Guernsey">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR" />
			<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="LIBERATION" />
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="im"
		description="Isle of Man">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR" />
			<tns:Fixed month="JULY" day="5" descriptionPropertiesKey="TYNWALD" />
			<tns:FixedWeekday which="SECOND" weekday="FRIDAY"
				month="JUNE" descriptionPropertiesKey="TOURIST_TROPHY" />
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="je"
		description="Jersey">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR" />
			<tns:Fixed month="MAY" day="9" descriptionPropertiesKey="LIBERATION" />
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="ni"
		description="Northern Ireland">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR" />
			<tns:Fixed month="MARCH" day="17" descriptionPropertiesKey="ST_PATRICK">
				<tns:MovingCondition substitute="SATURDAY" with="NEXT"
					weekday="MONDAY" />
				<tns:MovingCondition substitute="SUNDAY" with="NEXT"
					weekday="MONDAY" />
			</tns:Fixed>
			<tns:Fixed month="JULY" day="12" descriptionPropertiesKey="BATTLE_BOYNE">
				<tns:MovingCondition substitute="SATURDAY" with="NEXT"
					weekday="MONDAY" />
				<tns:MovingCondition substitute="SUNDAY" with="NEXT"
					weekday="MONDAY" />
			</tns:Fixed>
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="sc"
		description="Scotland">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR">
				<tns:MovingCondition substitute="SATURDAY" with="NEXT"
					weekday="TUESDAY" />
				<tns:MovingCondition substitute="SUNDAY" with="NEXT"
					weekday="TUESDAY" />
			</tns:Fixed>
			<tns:Fixed month="JANUARY" day="2"
				descriptionPropertiesKey="NEW_YEAR">
				<tns:MovingCondition substitute="SATURDAY" with="NEXT"
					weekday="MONDAY" />
				<tns:MovingCondition substitute="SUNDAY" with="NEXT"
					weekday="MONDAY" />
			</tns:Fixed>
			<tns:FixedWeekday which="FIRST" weekday="MONDAY"
				month="AUGUST" descriptionPropertiesKey="BANK_HOLIDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
	<tns:SubConfigurations hierarchy="wa"
		description="Wales">
		<tns:Holidays>
			<tns:Fixed month="JANUARY" day="1"
				descriptionPropertiesKey="NEW_YEAR">
				<tns:MovingCondition substitute="SATURDAY" with="NEXT"
					weekday="MONDAY" />
				<tns:MovingCondition substitute="SUNDAY" with="NEXT"
					weekday="MONDAY" />
			</tns:Fixed>
			<tns:FixedWeekday which="FIRST" weekday="MONDAY"
				month="AUGUST" descriptionPropertiesKey="BANK_HOLIDAY" />
			<tns:ChristianHoliday type="EASTER_MONDAY" />
		</tns:Holidays>
	</tns:SubConfigurations>
</tns:Configuration>
